### ISSUE TITLE
ImagickException Failed to read the file

### ISSUE THREAD

**Issue by leonidas-o** [crater-invoice/crater#1009]
Running on Crater 6.0.6 via Docker (rootless Podman)
Deployed it like described here: https://github.com/crater-invoice/crater/issues/844#issuecomment-1208170952
(podman 4.1.1 with podman-compose 1.0.3, so docker-compose.yml was used)

At the beginning I had a memory exceeded issue when I wanted to view the invoice in the preview, so in the file `docker-compose/php/uploads.ini` I added `memory_limit = 512M`. I still had the same error message, so I increased the memory limit to `1024M`. The memory exceeded is now gone but I get a `ImagickException Failed to read the file` error.

1. Is this behaviour expected and wanted that per default memory limit setting, an invoice preview can't be generated (using the default invoice1 template)?
2. Any suggestions what to do to solve the ImagickException?

**Comment by mohitpanjwani** [comment]
Glad to know that you figured out the issue. We use DOMPDF internally to render/generate PDFs so it might be an issue with that.
