### ISSUE TITLE
PDF Error (Server Error 500)

### ISSUE THREAD

**Issue by Surgical71** [crater-invoice/crater#1018]
Unable to display any invoices or PDF's

**Screenshots**
![image](https://user-images.githubusercontent.com/80483431/185142080-aeaf07e7-deb8-4605-8bb1-ab3589f6fca5.png)

**Please complete the following information:**
- Crater version: V6

**Optional info**
- OS:  Ubuntu
- Browser: Chrome

**Comment by mohitpanjwani** [comment]
Can you enable debugging to see the error: `APP_DEBUG=true`?

**Comment by mohitpanjwani** [comment]
Closing this but feel free to reopen if you still cannot fix it.
