### ISSUE TITLE
Crater crashes when restarting containers

### ISSUE THREAD

**Issue by stefanp88** [crater-invoice/crater#1019]
I use portainer to manage my docker containers running in a LXC container.
Whenever I restart my docker containers the app crashed completely and I have to restore a backup I took on my hypervisor.

![image](https://user-images.githubusercontent.com/31329306/185530620-45eba48f-04f6-489d-be73-356e8077386a.png)

Error message:
lluminate\Database\QueryException
SQLSTATE[HY000] [2002] Connection refused (SQL: select * from information_schema.tables where table_schema = crater and table_name = abilities and table_type = 'BASE TABLE')

- Crater version: 6.0.6
- PHP version:  PHP 7.4.3 (cli) (built: Jun 13 2022 13:43:30) ( NTS )
- Database type and version: mariadb

- OS:  Debian 10
- Browser: chrome

**Comment by mohitpanjwani** [comment]
> I use portainer to manage my docker containers running in a LXC container. Whenever I restart my docker containers the app crashed completely and I have to restore a backup I took on my hypervisor.
> 
> ![image](https://user-images.githubusercontent.com/31329306/185530620-45eba48f-04f6-489d-be73-356e8077386a.png)
> 
> Error message: lluminate\Database\QueryException SQLSTATE[HY000] [2002] Connection refused (SQL: select * from information_schema.tables where table_schema = crater and table_name = abilities and table_type = 'BASE TABLE')
> 
> * Crater version: 6.0.6
> * PHP version:  PHP 7.4.3 (cli) (built: Jun 13 2022 13:43:30) ( NTS )
> * Database type and version: mariadb
> * OS:  Debian 10
> * Browser: chrome

Make sure that your database container is running without error and the database env credentials are correct because based on the error that you've pasted, it looks like it's unable to connect to the database.

**Comment by mohitpanjwani** [comment]
Closing this now but feel free to reopen if you cannot find a solution.

**Comment by p0se** [comment]
I had the same problem.
It looks like the crater-db-1 container changes the IP after the first reboot. 
After I adjusted the IP in the .env it works. 
The DB container now also keeps its IP.
