### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by realkaldy** [crater-invoice/crater#1021]
**Describe the bug**
I have followed the manual installation instruction. When I try to access the url (/public_html/accounting/) to start the setup I have this error: (the accounting is a sub domain

```
Internal Server Error

The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at webmaster@accounting.hostexodus.co.za to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log.

Additionally, a 500 Internal Server Error error was encountered while trying to use an ErrorDocument to handle the request.
```

**Expected behavior**
Access the setup page after manual installation

**Screenshots**

**Please complete the following information:**
- Crater version: CRATER_6.0.6
- PHP version: PHP 7.4
- Database type and version: Didn't set it yet

**Optional info**
- OS:  Linux, cPanel 104.0 (build 8)
- Browser: Opera GX

**Comment by mpember** [comment]
As the message in your browser states:
_"More information about this error may be available in the server error log."_

Check your server's error logs.  It is possible that you are missing a required module or have an incorrect setting somewhere.

**Comment by mohitpanjwani** [comment]
You can enable debugging by changing your `.env` file and updating `APP_DEBUG=true` to see the error.

**Comment by nathalizator** [comment]
Did you find a solution to fix this @realkaldy ? Are you on shared hosting ?
