### ISSUE TITLE
[BUG] "Send invoices as attachments" config is not used/respected by the application

### ISSUE THREAD

**Issue by azaricstefan** [crater-invoice/crater#1038]
**Describe the bug**
Setting for "Send invoices as attachments" is ignored and value is always true.
Setting description: "Enable this if you want to send invoices as email attachment. Please note that 'View Invoice' button in emails will not be displayed anymore when enabled."
Client always get's PDF attachment and there is no way to get a button to open an Invoice online.

**Expected behavior**
This setting is working as it should. Customer indeed gets a button to view his invoice and PDF is not attached.

**Screenshots**
![Screenshot 2022-09-16 at 23 58 49](https://user-images.githubusercontent.com/9116773/190809180-7f57c6a6-8c64-49c7-a55f-2f5782b2722e.png)

**Please complete the following information:**
- Crater version: latest 
- PHP version: 7.4
- Database type and version: mysql 8

**Comment by agencetwogether** [comment]
It's working as it should for me Crater 6.0.6
If I check this option, invoice is attached to email. If not checked, invoice can view with button inside email body.

**Comment by azaricstefan** [comment]
Solution was to insert row: "estimate_email_attachment" and "invoice_email_attachment" inside the company_settings table.

This wasn't done with the migrations automatically somehow.

Closing the issue.
