### ISSUE TITLE
Could not read configuration from PHP

### ISSUE THREAD

**Issue by bsaeed2312** [crater-invoice/crater#1062]
I am facing error while running yarn dev and getting error. Picture Attached
![yarn dev error](https://user-images.githubusercontent.com/75486602/194750860-3caebcc6-8fa2-4af2-9ccb-aa37fd6a6d1a.png)

**Comment by mohitpanjwani** [comment]
What do you get if you run `php artisan route:list` command on console? 

internally yarn dev tries to get the configuration from PHP which doesn't seem to be working.
