### ISSUE TITLE
Suddenly not able to login anymore

### ISSUE THREAD

**Issue by philharmonie** [crater-invoice/crater#1064]
**Describe the bug**
I am using crater for a while and suddenly I am not able to login anymore.
Beside that, randomly when I reload the page, I get a text `File not found.` displayed in the browser. When I reload again, the login screen appears:
```
192.168.112.3 -  11/Oct/2022:07:18:26 +0000 "GET /index.php" 404
192.168.112.3 -  11/Oct/2022:07:19:54 +0000 "GET /index.php" 200
```

When I try to login, I get a notification pop up with:
```
Error
something went wrong
```
There is no error in the container logs and I checked the path `storage/logs` but it does not have a log with the date of today.

**Expected behavior**
Login should work as usual.

**Please complete the following information:**
- Crater version: 6.0.6
- Docker version

**Optional info**
- Browser: Tried Safari, Chrome and iOS app

**Comment by mohitpanjwani** [comment]
I think something must have went wrong with your docker containers. 

Can you try enabling debugging by adding `APP_DEBUG=true` on your .env file?

**Comment by philharmonie** [comment]
When you blindly follow the docker installation steps (`cp .env.example .env`) in the docs, this is the default setting. Same for me. And the error displayed on the screen is a well designed UI error notification and nothing caught by an exception that stops the app. Is I have a feeling, there is something wrong with nginx, I checked the logs there and found:
```
192.168.112.11 - - [14/Oct/2022:14:19:07 +0000] "GET /login HTTP/1.1" 404 27 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.1 Safari/605.1.15"
2022/10/14 14:19:07 [error] 10#10: *18 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 192.168.112.11, server: , request: "GET /login HTTP/1.1", upstream: "fastcgi://192.168.112.8:9000", host: "my.host.domain"
2022/10/14 14:23:30 [error] 10#10: *41 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 192.168.112.11, server: , request: "POST /login HTTP/1.1", upstream: "fastcgi://192.168.112.8:9000", host: "my.host.domain", referrer: "https://my.host.domain/login"
192.168.112.11 - - [14/Oct/2022:14:22:09 +0000] "POST /login HTTP/1.1" 404 27 "https://my.host.domain/login" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.1 Safari/605.1.15"
```
I removed all the 200 rows. If they are interesting, I'll add them.

**Comment by philharmonie** [comment]
I was wondering about the php proxy pass and was able to find another service called app on the same docker network. After providing more unique service names (and updating the db host and nginx php config) everything is working fine again. Thank you for the hint to the container setup in general.
