### ISSUE TITLE
Missing hyphen in setup.sh

### ISSUE THREAD

**Issue by daramayis** [crater-invoice/crater#1066]
### Descrption

People usually have `docker-compose` and so `docker compose` doesn't work. And it's better to have just `docker-compose` instead of both `docker compose` and `docker-compose` inside https://github.com/crater-invoice/crater/blob/38c4b9ebced6d75d7fd4f4e7a1ae45f6a5604fd8/docker-compose/setup.sh#L3-L7

**Describe the bug**
In `setup.sh` missing `-` between `docker` and `compose`. Line 3.
Actual: `docker compose exec app composer config --no-plugins allow-plugins.pestphp/pest-plugin true`

**Expected behavior**
Should be: `docker-compose exec app composer config --no-plugins allow-plugins.pestphp/pest-plugin true`

**Comment by mohitpanjwani** [comment]
Thanks for the fix 👌
