### ISSUE TITLE
AUTH_TOKEN API retrieving: GET method not supported with POST

### ISSUE THREAD

**Issue by JeroenSteen** [crater-invoice/crater#1077]
I'm trying to get the AUTH_TOKEN to use the API, and saw Introductions in docs talking about that a POST request is needed to api/v1/auth/login to get the token. I tried doing a POST request with Postman app to api/v1/auth/login/ with header company and value 1, but as a result I'm getting this error:

`Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException: The GET method is not supported for this route. Supported methods: POST. in file /home/domainnl/domains/domain.nl/public_html/crater/vendor/laravel/framework/src/Illuminate/Routing/AbstractRouteCollection.php on line 117`

**Comment by mohitpanjwani** [comment]
Are you trying it out using postman or something? 

Make sure you have Accept application/json header present.

**Comment by JeroenSteen** [comment]
I use Postman v9.31.0, and I made sure I have at Headers the Key "Accept" with Value application/json, that gives a JSON response indeed. I now notice their is a difference between api/v1/auth/login/ and api/v1/auth/login.

The api/v1/auth/login is the correct one, now getting "The given data was invalid" asking about user_name, password and device_name. Thanks [mohitpanjwani](https://github.com/mohitpanjwani).

**Comment by mohitpanjwani** [comment]
Great! 👍
