### ISSUE TITLE
Error ERR_ABORTED 404 and White Screen

### ISSUE THREAD

**Issue by 161134077** [crater-invoice/crater#1089]
Information:
<ol>
  <li> OS:Linux 22.04 using CLoud Panel </li>
  <li> PHP version: PHP 7.4 </li>
</ol>

I migrate old server directadmin to new server cloudpanel.

I do Migrate:
1. Move file to server cloudpanel.
2. Upload database
3. .env change username and password database

thanks..

![error](https://user-images.githubusercontent.com/39833970/201470626-4ae17559-49f1-4f05-bb14-c2d5ec365c87.PNG)

source code vhost:
<pre>
<code>
server {
  listen 8080;
  listen [::]:8080;
  server_name invoicee.website.com;
  {{root}}
  
  try_files $uri $uri/ /index.php?$args;
  index index.php index.html serve.php public/$1;
    
  location ~ \.php$ {
    include fastcgi_params;
    fastcgi_intercept_errors on;
    fastcgi_index index.php;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    try_files $uri =404;
    fastcgi_read_timeout 3600;
    fastcgi_send_timeout 3600;
    fastcgi_param HTTPS "on";
    fastcgi_pass 127.0.0.1:{{php_fpm_port}};
    fastcgi_param PHP_VALUE "{{php_settings}}";
  }

  if (-f $request_filename) {
    break;
  }
}

server {
  listen 80;
  listen [::]:80;
  listen 443 ssl http2;
  listen [::]:443 ssl http2;
  {{ssl_certificate_key}}
  {{ssl_certificate}}
  server_name invoicee.website.com;
  {{root}}

  {{nginx_access_log}}
  {{nginx_error_log}}

  if ($scheme != "https") {
    rewrite ^ https://$host$uri permanent;
  
  }

  location ~ /.well-known {
    auth_basic off;
    allow all;
  }

  {{settings}}

  location / {
    {{varnish_proxy_pass}}
    proxy_set_header Host $http_host;
    proxy_set_header X-Forwarded-Host $http_host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_hide_header X-Varnish;
    proxy_redirect off;
    proxy_max_temp_file_size 0;
    proxy_connect_timeout      720;
    proxy_send_timeout         720;
    proxy_read_timeout         720;
    proxy_buffer_size          128k;
    proxy_buffers              4 256k;
    proxy_busy_buffers_size    256k;
    proxy_temp_file_write_size 256k;
  }
    
  location ~* ^.+\.(css|js|jpg|jpeg|gif|png|ico|gz|svg|svgz|ttf|otf|woff|woff2|eot|mp4|ogg|ogv|webm|webp|zip|swf|map)$ {
    add_header Access-Control-Allow-Origin "*";
    expires max;
    access_log off;
  }

  if (-f $request_filename) {
    break;
  }
}
</code>
</pre>

**Comment by C0pywriting** [comment]
how was this solved?
