### ISSUE TITLE
Latest Crater package is 404

### ISSUE THREAD

**Issue by biosocket** [crater-invoice/crater#1209]
Step 1 of the [manual installation instructions](https://docs.craterapp.com/installation.html#manual-installation) is to download the latest crater package. However when you click [the download link](http://crater.financial/downloads), you get a 404 page.

I would expect the link to prompt a file download or display a page with a link to the download.

**Comment by mohitpanjwani** [comment]
Fixed on the new documentation site: https://docs.craterapp.com/installation.html
