### ISSUE TITLE
Allow customers to pay using Stripe

### ISSUE THREAD

**Issue by macbookandrew** [crater-invoice/crater#124]
**Is your feature request related to a problem? Please describe.**
I would love to be able to accept payments from customers using Stripe.

**Describe the solution you'd like**
When sending an email to customers, they would contain a link to the invoice as well as a link to pay online, and Crater would use the Stripe SDK to process payments and record payments.

**Comment by macbookandrew** [comment]
It would entail adding the [Stripe SDK](https://github.com/stripe/stripe-php), settings for Stripe API keys, and a new view/controller to handle payments.

Sample code for processing a payment through Stripe, taken from a similar project I built for myself:

```php
        try {
            $charge = \Stripe\Charge::create([
                'amount' => $request->input('amount') * 100,
                'currency' => 'usd',
                'description' => $description,
                'source' => $request->input('stripeToken'),
                'metadata' => ['Invoice', $invoice_id],
            ]);

            if ($charge->id) {
                $payment = new Payment();
                $payment->date = date('Y-m-d');
                $payment->method = 'stripe';
                $payment->amount = ($charge->amount / 100);
                $payment->details = $charge->id;
                $payment->save();

                if (isset($invoice_id)) {
                    $invoice = Invoice::find($invoice_id);
                    $payment->invoice()->associate($invoice);
                    $payment->user()->associate($invoice->user);

                    $payment->save();
                    $invoice->updatePayment();
                } elseif ($request->has('user_id')) {
                    $user = User::find($request->input('user_id'));
                    $payment->user()->associate($user);
                    $payment->save();
                }
            }
            return redirect()->action('InvoiceController@showPublic', ['id' => $payment->invoice->hashid()]);
        } catch (\Stripe\Exception\RateLimitException $e) {
            // Too many requests made to the API too quickly
            return back()->withErrors('Error! ' . $e->getMessage());
        } catch (\Stripe\Exception\InvalidRequestException $e) {
            // Invalid parameters were supplied to Stripe's API
            return back()->withErrors('Error! ' . $e->getMessage());
        } catch (\Stripe\Exception\AuthenticationException $e) {
            // Authentication with Stripe's API failed
            // (maybe you changed API keys recently)
            return back()->withErrors('Error! ' . $e->getMessage());
        } catch (\Stripe\Exception\ApiConnectionException $e) {
            // Network communication with Stripe failed
            return back()->withErrors('Error! ' . $e->getMessage());
        } catch (\Stripe\Exception\ApiErrorException $e) {
            // Display a very generic error to the user, and maybe send
            // yourself an email
            return back()->withErrors('Error! ' . $e->getMessage());
        } catch (Exception $e) {
            // Something else happened, completely unrelated to Stripe
            return back()->withErrors('Error! ' . $e->getMessage());
        }
```

**Comment by mohitpanjwani** [comment]
Hey! This is definitely on the list. 

We've made some progress as well but it'll take some time before its ready for release.

**Comment by rizdem** [comment]
will you be making it SCA compliant as eu regulations?

**Comment by jcs224** [comment]
Any updates? Blockers?

**Comment by mohitpanjwani** [comment]
We have decided to add this as a separate paid module. 

Right now our focus is to release 4.0 which contains following: 
- Replace Bootstrap with TailwindCSS
- Backup ( Create File and DB backups with UI)
- Customer View page
- Custom Notes
- Unit & Feature Tests
- Cleaner and simpler API and API Documentation
- Edit Email Subject & Description with placeholders before sending out an Invoice or Estimate Email
- Custom Fields with custom address formats for invoices, estimates and payment receipts
- Global Search
- File Disk configuration ( supports Local, Digital Ocean spaces, AWS S3 and Dropbox drivers )

**Comment by karneaud** [comment]
@mohitpanjwani good looking out. I was looking to see if crater had a modular way to add payment gateways...I've worked on a couple stuff using #invoiceNinja and I have integrated custom gateways using the https://github.com/thephpleague/omnipay library. Perhaps looking into https://github.com/thephpleague/omnipay-stripe for some standard ways for modularizing payment gateways for crater

**Comment by ekiel** [comment]
Any update?

**Comment by mohitpanjwani** [comment]
> Any update?

Modules are coming in November end or early December.

**Comment by anondev-sudo** [comment]
This is really good idea to add online payments, will you support PayPal too? 

When you click on the invoice link, there should be Pay now button when it's enabled that will show dropdown menu of available payment gateways.

https://paypal.github.io/PayPal-PHP-SDK/
https://developer.paypal.com/docs/api/overview/

**Comment by mohitpanjwani** [comment]
> This is really good idea to add online payments, will you support PayPal too?
> 
> When you click on the invoice link, there should be Pay now button when it's enabled that will show dropdown menu of available payment gateways.
> 
> https://paypal.github.io/PayPal-PHP-SDK/ https://developer.paypal.com/docs/api/overview/

Yes, the intial version of the module will support 3 payment methods:
- Paypal
- Stripe
- RazorPay

we will continue adding support for more payment methods as required.

**Comment by anondev-sudo** [comment]
Is there ETA when it will be released?

**Comment by mohitpanjwani** [comment]
> Is there ETA when it will be released?

Around end of this month.

**Comment by anondev-sudo** [comment]
I think that it is currently added but just as paid module, it should be included in the invoice software, not as paid addon. For example invoice plane supports online payments but it's whole not maintenaned (drives are outdated, for example it just has paypal express api, not normal paypal api).



![](https://media.discordapp.net/attachments/856871839820677130/931543222860271636/unknown.png)

**Comment by javaskript** [comment]
> I think that it is currently added but just as paid module, it should be included in the invoice software, not as paid addon.

I agree, this common feature should be included in the core functionality. However, I presume that the project maintainers will disagree. This module not being free/open source itself requires me to look elsewhere for my invoicing software.

**Comment by mohitpanjwani** [comment]
@anondev-sudo @javaskript Thanks for the feedback and we really appreciate your support but unfortunately right now we have no plans to include this feature in the core free version. 

Closing this issue as this feature is already released as a module.

**Comment by maha-oueghlani** [comment]
> > This is really good idea to add online payments, will you support PayPal too?
> > When you click on the invoice link, there should be Pay now button when it's enabled that will show dropdown menu of available payment gateways.
> > https://paypal.github.io/PayPal-PHP-SDK/ https://developer.paypal.com/docs/api/overview/
> 
> Yes, the initial version of the module will support 3 payment methods:
> 
>     * Paypal
> 
>     * Stripe
> 
>     * RazorPay
> 
> 
> we will continue adding support for more payment methods as required.

@mohitpanjwani  is PayPal available now ? if yes how I cant get this module plz ?
