### ISSUE TITLE
Reviving Crater - An Open-Source Invoicing & Bill Pay Project

### ISSUE THREAD

**Issue by omaratpxt** [crater-invoice/crater#1254]
Dear Developers and Crater Fans,

I hope this message finds you well. I am writing to draw your attention to an exciting opportunity to revive a once-promising project, Crater. As some of you may already be aware, the original project seems to have gone dormant, but I believe it has significant potential to make a positive impact on the open-source community and beyond.

Crater's potential lies in its ability to streamline invoicing and bill payment processes, which are essential aspects of many businesses. Unfortunately, the original developers may have moved on to other projects, leading to a halt in development. However, we have the power to breathe new life into this project and bring it back to the forefront of open-source innovation.

My proposal is to fork the existing project repository at "https://github.com/pixxet/crater" and form a dedicated team of like-minded individuals who share the vision of rejuvenating Crater. With collective effort and commitment, we can make the following contributions to this project:

Why Revive Crater?
1. Valuable Project: Crater, in its initial form, provided a powerful tool for invoicing and bill payment within platforms. Many users found it useful for managing financial transactions, and it offered a unique value proposition.

2. Community Interest: Despite the original project's inactivity, the community surrounding Crater has shown continued interest. Various online discussions, support forums, and social media posts demonstrate the project's potential and importance to developers and businesses.

3. Learn from Past: By forking Crater, we can learn from its strengths and shortcomings, build upon the foundation laid by the original developers, and address any issues that led to its decline. This way, we can ensure that the revitalized project is more sustainable and successful.

4. Showcase of Skills: Working on a well-established open-source project like Crater allows developers to showcase their abilities, collaborate with others, and gain valuable experience in handling complex software projects.

How to Revive Crater:
1. Establish a Fork: The first step is to create a fork of the original Crater repository. By doing so, we preserve the existing codebase while creating a new space for future development.

2. Assemble a Team: Recruit passionate developers, designers, testers, and project managers who are enthusiastic about the project's potential. Collaboration and diversity in skillsets will be crucial for the project's success.

3. Conduct a Thorough Review: Assess the existing codebase, documentation, and open issues to understand the project's current state. Identify the primary pain points, bugs, and missing features that need attention.

4. Prioritize Tasks: Plan a roadmap for the project's revival, focusing on addressing the most critical issues first. Aim to deliver incremental improvements to maintain momentum and engagement.

5. Community Engagement: Encourage participation from the existing Crater community and beyond. Reach out to previous contributors, notify users of the fork, and actively engage in discussions to gather feedback and ideas.

6. Update Dependencies and Security: Ensure that the project's dependencies are up-to-date, and address any security vulnerabilities that may have arisen during the period of inactivity.

7. Improve Documentation: Enhance the project's documentation, making it more accessible for new contributors and users. Comprehensive guides and tutorials will aid in the project's adoption and success.

8. Foster a Collaborative Environment: Encourage open communication and create a welcoming atmosphere for contributors. Emphasize the value of teamwork and acknowledge all contributions, big or small.

9. Publicize the Revival: Share the news of the revived Crater project across relevant online platforms, tech forums, and social media channels. This will attract more users and contributors to join the community.

10. Continuous Improvement: Commit to regular updates and improvements. Encourage a culture of continuous development and learning to keep the project relevant and responsive to user needs.

Let's work together to make the revival of Crater a reality. By forking the project and fostering a vibrant community, we can reclaim its potential and build an exceptional open-source invoicing and bill pay platform that benefits users worldwide. Together, we can make a difference!

If you're interested in joining this initiative, please reply to this email or reach out on our dedicated communication channels.

Let's bring Crater back to life and embark on an exciting journey of open-source collaboration!

Best regards,

Omar

**Comment by agencetwogether** [comment]
Hello I want to be include in this new journey. Good idea. I made a big PR (https://github.com/crater-invoice/crater/pull/1020) but meanwhile mohitpanjwani liked, this PR will never mergedSo I like this tool Crater, and I will be happy if it can revive….Cheers#Le 2 août 2023 à 21:02, pixxet ***@***.***> a écrit :﻿
Dear Developers and Crater Fans,
I hope this message finds you well. I am writing to draw your attention to an exciting opportunity to revive a once-promising project, Crater. As some of you may already be aware, the original project seems to have gone dormant, but I believe it has significant potential to make a positive impact on the open-source community and beyond.
Crater's potential lies in its ability to streamline invoicing and bill payment processes, which are essential aspects of many businesses. Unfortunately, the original developers may have moved on to other projects, leading to a halt in development. However, we have the power to breathe new life into this project and bring it back to the forefront of open-source innovation.
My proposal is to fork the existing project repository at "https://github.com/pixxet/crater" and form a dedicated team of like-minded individuals who share the vision of rejuvenating Crater. With collective effort and commitment, we can make the following contributions to this project:
Why Revive Crater?


Valuable Project: Crater, in its initial form, provided a powerful tool for invoicing and bill payment within platforms. Many users found it useful for managing financial transactions, and it offered a unique value proposition.


Community Interest: Despite the original project's inactivity, the community surrounding Crater has shown continued interest. Various online discussions, support forums, and social media posts demonstrate the project's potential and importance to developers and businesses.


Learn from Past: By forking Crater, we can learn from its strengths and shortcomings, build upon the foundation laid by the original developers, and address any issues that led to its decline. This way, we can ensure that the revitalized project is more sustainable and successful.


Showcase of Skills: Working on a well-established open-source project like Crater allows developers to showcase their abilities, collaborate with others, and gain valuable experience in handling complex software projects.


How to Revive Crater:


Establish a Fork: The first step is to create a fork of the original Crater repository. By doing so, we preserve the existing codebase while creating a new space for future development.


Assemble a Team: Recruit passionate developers, designers, testers, and project managers who are enthusiastic about the project's potential. Collaboration and diversity in skillsets will be crucial for the project's success.


Conduct a Thorough Review: Assess the existing codebase, documentation, and open issues to understand the project's current state. Identify the primary pain points, bugs, and missing features that need attention.


Prioritize Tasks: Plan a roadmap for the project's revival, focusing on addressing the most critical issues first. Aim to deliver incremental improvements to maintain momentum and engagement.


Community Engagement: Encourage participation from the existing Crater community and beyond. Reach out to previous contributors, notify users of the fork, and actively engage in discussions to gather feedback and ideas.


Update Dependencies and Security: Ensure that the project's dependencies are up-to-date, and address any security vulnerabilities that may have arisen during the period of inactivity.


Improve Documentation: Enhance the project's documentation, making it more accessible for new contributors and users. Comprehensive guides and tutorials will aid in the project's adoption and success.


Foster a Collaborative Environment: Encourage open communication and create a welcoming atmosphere for contributors. Emphasize the value of teamwork and acknowledge all contributions, big or small.


Publicize the Revival: Share the news of the revived Crater project across relevant online platforms, tech forums, and social media channels. This will attract more users and contributors to join the community.


Continuous Improvement: Commit to regular updates and improvements. Encourage a culture of continuous development and learning to keep the project relevant and responsive to user needs.


Let's work together to make the revival of Crater a reality. By forking the project and fostering a vibrant community, we can reclaim its potential and build an exceptional open-source invoicing and bill pay platform that benefits users worldwide. Together, we can make a difference!
If you're interested in joining this initiative, please reply to this email or reach out on our dedicated communication channels.
Let's bring Crater back to life and embark on an exciting journey of open-source collaboration!
Best regards,
Omar

**Comment by Syam** [comment]
Hi there,

I am interested in using crater, but missing some features like : 
- credit invoice
- deposit invoice
- balance invoice
- bulk upload files to expenses + quick edit
- import expenses from api bank account
- default VAT/settings to apply to invoices

I am planning to add theses features for myself, but would be happy to push update to your fork.

Any suggestion of collaboration process ?

**Comment by omaratpxt** [comment]
Hello @Syam,

I'm glad to hear that you're interested, and glad to hear that you already have some exciting ideas for adding new features! 
Your contributions could greatly enhance the project and benefit the entire community. Here's a suggestion for a collaboration process to make the integration of these features smooth and effective:

1. Feature Proposal: Start by opening an issue or discussion for each new feature you'd like to add, outlining your ideas and gathering input from the community.

2. Branches and Coding: Create separate branches for each feature in your forked repository and implement the changes following project guidelines.

3. Regular Updates: Keep the community informed by creating pull requests from your feature branches to the main repository, ensuring a consistent feedback loop.

4. Testing and Documentation: Thoroughly test the features and update the documentation to explain their usage and benefits.

5. Review and Merge: Collaborate with project maintainers (we need to ensure having multiple maintainers) for reviews and merging of your features into the main repository.

6. Compatibility Maintenance: Stay engaged by updating your features to align with ongoing changes in the main project.

7. Engage and Communicate: Stay open to feedback and engage with the community, contributing to Crater's growth and success.

Our efforts will not only enhance Crater but also empower its users and developers. Thank you everyone for your dedication to improving this open-source platform.


For any further communication we are using: https://github.com/pixxet/crater

**Comment by jenishngl** [comment]
Lets check https://github.com/pixxet/crater/issues/3

**Comment by rihards-simanovics** [comment]
hey @pixxet just navigated to the project repo and noticed that it is archived, any reason for that?

**Comment by omaratpxt** [comment]
https://github.com/pixxet/crater/discussions/4

**Comment by rihards-simanovics** [comment]
oh, I see, sorry didn't notice the discussion tab 😅.

I understand, was thinking of taking over the maintenance myself then realise when weighing the pros and cons of taking over the codebase that is too large. it would be too much for me to handle alone especially with the uni. studies I am doing now.

It's sad and unfortunate, but I think that any accounting software is not really made for FOS. Banks will never make their API publicly accessible for anyone to use and it's just too much work to account for every country need. One country needs "x", another "y", and different one "i", I'm not even going to mention the date formatting, types of reports, etc. Crater team has wisely just stuck with American Large companies, and that's it, otherwise it's too much work for one team.

**Comment by rihards-simanovics** [comment]
For anyone who stumbles across this discussion please see this issue for links to new fork: https://github.com/crater-invoice/crater/issues/1265
