### ISSUE TITLE
Currency Missing: LYD

### ISSUE THREAD

**Issue by MohamedBakoush** [crater-invoice/crater#1293]
**Is your feature request related to a problem? Please describe.**
The Libyan Currency is missing in CurrenciesTableSeeder.

**Describe the solution you'd like**

Add to CurrenciesTableSeeder
```
          [
              'name' => 'Libyan Dinar',
              'code' => 'LYD',
              'symbol' => 'LD',
              'precision' => '3',
              'thousand_separator' => ',',
              'decimal_separator' => '.',
          ]
```
Allowing the LYD Currency to be used in Crater.

**Comment by rihards-simanovics** [comment]
quick reminder the software is abandonware and will no longer receive updates: https://github.com/crater-invoice/crater/issues/1265

**Comment by rihards-simanovics** [comment]
# ❗Attention❗
Please migrate to InvoiceShelf, a fork of crater which continues the development of this project.

More info on new fork availible in this issue: #1281
