### ISSUE TITLE
Page not redirecting after login

### ISSUE THREAD

**Issue by RappyTV** [crater-invoice/crater#1299]
**Describe the bug**

Followup for #391. I get an error when trying to log in and the console says "Mixed content"

**Expected behavior**
I get redirected to `/admin/dashboard`

**Screenshots**
![image](https://github.com/crater-invoice/crater/assets/72705182/1fa42719-5547-416f-91f6-cf715ee4420a)
![image](https://github.com/crater-invoice/crater/assets/72705182/24835b9c-1e87-4931-a879-649675297c5f)

**Please complete the following information:**
- Crater version: 6.0.6
- PHP version: idk
- Database type and version: mariadb latest

**Optional info**
- OS: Ubuntu / Docker
- Browser: *
- I'm using nginx as the proxy. My proxy file:
```nginx
server {
    include /etc/nginx/conf.d/listen_plain.active;
    include /etc/nginx/conf.d/listen_ssl.active;
    ssl_certificate /etc/letsencrypt/live/***/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/***/privkey.pem;
    include /etc/nginx/conf.d/ssl.active;
    include /etc/nginx/conf.d/errors.active;
    server_name ***;

    location / {
        proxy_pass http://127.0.0.1:7126/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
```

**Comment by rihards-simanovics** [comment]
quick reminder the software is abandonware and will no longer receive updates: https://github.com/crater-invoice/crater/issues/1265

**Comment by rihards-simanovics** [comment]
# ❗Attention❗
Please migrate to InvoiceShelf, a fork of crater which continues the development of this project.

More info on new fork availible in this issue: #1281
