### ISSUE TITLE
Already created invoices should not be updated with new details

### ISSUE THREAD

**Issue by lawzava** [crater-invoice/crater#217]
**Describe the bug**
After creating & resolving an invoice, updating the company details later updated the details on the invoice too.

**Expected behavior**
Details should never be updated on already sent/paid invoices. They should always remain as-is.

**Please complete the following information:**
- Crater version: 3.1.0
- PHP version: 7.4
- Database type and version: PostgreSQL 12

**Comment by mwikala** [comment]
I wouldn't consider this to be a bug, there is no legal implications that I know of at least in the United Kingdom that would consider a sent/paid invoice voided if the company details change.

If you have a valid reason for this being added then please feel free to leave a comment and we can reconsider working on this. Thanks for your issue.
