### ISSUE TITLE
Recurring Payments

### ISSUE THREAD

**Issue by makakken** [crater-invoice/crater#366]
**Is your feature request related to a problem? Please describe.**
Every 3 Months i Have to invoice my customers. Every three months the same items on the invoice. wouldn't it be nice if i coul automatically generate the bills all three monthts? (or maybe all 6 months? yearly?)

**Describe the solution you'd like**
I'd like to have a solution where i can choose:
- customer
- items
- recurring timespan (monthly? every 3 months? half a year? yearly?)
- 
**Describe alternatives you've considered**
Setting up a calendar reminder and generate invoices by myself. (annyoing ;) )

**Comment by mohitpanjwani** [comment]
Closing this coz Recurring Invoices are available from V5 onwards.
