### ISSUE TITLE
Cant change default Invoice Layout

### ISSUE THREAD

**Issue by makakken** [crater-invoice/crater#367]
**Describe the bug**
in /admin/settings/customization there is no option to change the default invoice layout

**Expected behavior**
having the choice which of the layouts i can set as default.

**Please complete the following information:**
- Crater version: 4.0.4
- PHP version: 7.4
- Database type and version: MySQL 5.6

**Comment by lawzava** [comment]
This feature is within the roadmap under `whitelabeling` 👍🏼

**Comment by NicoHood** [comment]
The roadmap says that this feature is completed, but there is still no way to set a new default.

**Comment by mohitpanjwani** [comment]
https://github.com/crater-invoice/crater/releases/tag/6.0.3

The ability to select the default invoice template was added on 6.0.3, @NicoHood which version are you on currently? 

![CleanShot 2022-04-01 at 12 01 37@2x](https://user-images.githubusercontent.com/8002555/161208022-a81522bb-a079-407b-ac5e-aada97cfa6b6.png)

**Comment by NicoHood** [comment]
I am using v 6.0.6, but I've added a custom layout. Now the option is gone it seems. After seeing your screenshot I remember that there was this option before.

![image](https://user-images.githubusercontent.com/6888294/161906363-ccc424ac-9673-4962-93f7-4a6c428d5eeb.png)
