### ISSUE TITLE
Login redirect issue

### ISSUE THREAD

**Issue by v6-cblais** [crater-invoice/crater#391]
**Describe the bug**

Error message when logging in: Network Error
Please check your internet connection or wait until servers are back online

If you change the url to /admin it completes the login successfully.

**Expected behavior**
-Redirect should be automatic

**Screenshots**
-Text of error above

**Please complete the following information:**
- Crater version: 4.0.4
-PHP version: not sure
-Database type and version: mariadb 10.5.8
    -Used the latest docker-compose cloned 1/28/2021

**Optional info**
- OS:  [e.g. Ubuntu] Ubuntu/Docker
- Browser: [e.g. chrome, safari] Edge/Brave/Firefox

**Comment by fazalfarhan01** [comment]
Have a similar issue. 
Shows on login, but refreshing the page redirects me to the `/admin/dashboard`.

```
Network Error
Please check your internet connection or wait until servers are back online
```

OS: Docker on Windows 10 WSL2 (Also tried on Ubuntu Server 20.04, issue persists.)
Browser: Chrome 90.0.4430.93

**Comment by JensVanhooydonck** [comment]
Redirect URL seems te be http instead of https
`Mixed Content: The page at 'https://crater.****/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://crater.****/admin/dashboard'. This request has been blocked; the content must be served over HTTPS.`

**Comment by v6-cblais** [comment]
@JensVanhooydonck  do you think this is something to do with how we are redirecting the site our how the site is handling it?

**Comment by JensVanhooydonck** [comment]
@v6-cblais Indeed, the scheme isn't enforced. I opened a PR which fixes this issue for me.

**Comment by davwheat** [comment]
This is still an issue on v5, and is actually bricking my upgraded instance. The APP_URL is https://... but the frontend assets are loaded with http://... for some reason.

**Comment by JensVanhooydonck** [comment]
> This is still an issue on v5, and is actually bricking my upgraded instance. The APP_URL is https://... but the frontend assets are loaded with http://... for some reason, meaning that the JS doesn't load, and the app is dead.

I guess something is wrong with your reverse proxy settings. I don't need the change anymore I've put in the PR.
However, I still did not upgrade to v5 yet.

**Comment by davwheat** [comment]
The reverse proxy is fine. The issue is that Crater's assets are being injected with http protocol links rather than https:

![](https://u.davwheat.dev/WRFzluee.png)
![](https://u.davwheat.dev/iQHfYowi.png)

**Comment by michael-dm** [comment]
I have the same problem than @davwheat, any news on this issue ?

**Comment by pepa65** [comment]
Another thing is that Crater sites often seem to get detected as deceptive/fishing sites...
