### ISSUE TITLE
Item arrangement order in Estimates changes after every small edit

### ISSUE THREAD

**Issue by gtomco** [crater-invoice/crater#410]
Every time I modify the estimate (even just a title of an item), the whole list of items gets rearranged in a different, random manner.

**Comment by mohitpanjwani** [comment]
We cannot reproduce this on our end. I think you might be missing an extension or something. 

Are you on Docker setup or manual one?

**Comment by gtomco** [comment]
I am on a manual setup. So far, the system has worked pretty well and very stable. I made sure I installed every required component. I made a small video recording where I reproduced the issue and uploaded it to Google Drive:
https://drive.google.com/file/d/1Tp_DPy94-w05FxQUjby-eKT54ErVOq3V/view?usp=sharing

**Comment by mohitpanjwani** [comment]
> I am on a manual setup. So far, the system has worked pretty well and very stable. I made sure I installed every required component. I made a small video recording where I reproduced the issue and uploaded it to Google Drive:
> https://drive.google.com/file/d/1Tp_DPy94-w05FxQUjby-eKT54ErVOq3V/view?usp=sharing

I still cannot reproduce this. 

Please provide more information mentioned in the issue template. 


**Please complete the following information:**
- Crater version: 
- PHP version: 
- Database type and version: 

**Optional info**
- OS:  [e.g. Ubuntu]
- Browser: [e.g. chrome, safari]
