### ISSUE TITLE
Missing transable keys

### ISSUE THREAD

**Issue by BIIINO** [crater-invoice/crater#444]
I want to translate few more phases which are currently not in any language (also not in english)

On reports tab, there are:
        'Today',
        'This Week',
        'This Month',
        'This Quarter',
        'This Year',
        'Previous Week',
        'Previous Month',
        'Previous Quarter',
        'Previous Year',
        'Custom',

I wan to add them as transable keys, but when i add them only to the en.js and sk.json, all these keys are still in english.

Please, where and how can i add more transable keys ?

Thank you

![image](https://user-images.githubusercontent.com/60783519/115140052-89c48280-a035-11eb-8857-532f327ca580.png)

**Comment by mohitpanjwani** [comment]
Fixed on V5.
