### ISSUE TITLE
🚨 Potential Security Vulnerability - huntr.dev

### ISSUE THREAD

**Issue by huntr-helper** [crater-invoice/crater#446]
#### ⚠️ Potential Vulnerability in crater

👋 Hello, @mohitpanjwani, @raishvaria, @Jay04Makwana - @ranjit-git has disclosed a potential vulnerability in your repository. To validate or invalidate this potential vulnerability, please visit https://huntr.dev/bounties/1-other-bytefury/crater and join our community in helping secure open-source code.

---

#### ☎️ Need further support?

Come and join us on our [Discord](https://huntr.dev/discord) and a member of our team will be happy to help! 🤗

cc - @JamieSlome

**Comment by mohitpanjwani** [comment]
Only admins have access to this endpoint. I don’t think this is a vulnerability.

**Comment by ranjit-git** [comment]
Hi, @mohitpanjwani @huntr-helper  No, all user has access to this endpoint . i just checked this features and see there has a features that admin can add lower level user (who does not have certain permission ). So, this lowerr level user can make xss attack against admin.

STEP
=========
1. goto https://demo.craterapp.com/admin/users from admin account and add a new user called userB . 
2. Now goto user B account and see userB does not have access to users module https://demo.craterapp.com/admin/users.  But userB has access to customer module https://demo.craterapp.com/admin/customers. 
3. So, now use B goto customer module and using the above mentioned  xss bug he can attack admin account and perform any task that admin can do .

**Comment by mohitpanjwani** [comment]
Right, Thanks for taking the time to find the vulnerability. 

Although right now the only user you can add is an admin, so he basically already has all the access he needs. There's no other role as of current release. 

But we've already implemented Roles + Permissions for next update so this is definitely useful for that. We'll make sure to test this out and fix this before that's released :)

**Comment by mohitpanjwani** [comment]
Keeping this open until it's fixed.

**Comment by ranjit-git** [comment]
@mohitpanjwani can you plz update the report status to valid here https://www.huntr.dev/bounties/1-other-bytefury/crater/

**Comment by ranjit-git** [comment]
> Right, Thanks for taking the time to find the vulnerability.
> 
> Although right now the only user you can add is an admin, so he basically already has all the access he needs. There's no other role as of current release.
> 
> But we've already implemented Roles + Permissions for next update so this is definitely useful for that. We'll make sure to test this out and fix this before that's released :)

Does role-permission based user implemented in the last release?
