### ISSUE TITLE
Would like the due date to not be required

### ISSUE THREAD

**Issue by jakeparis** [crater-invoice/crater#477]
I don't use due dates and would like their entry to be optional, rather than required. I could live with #176 if my request is not possible.

**Comment by mohitpanjwani** [comment]
We're on it. 

Thanks for the feedback.

**Comment by mohitpanjwani** [comment]
We're adding a default option as well as working on making it optional.

**Comment by mohitpanjwani** [comment]
Due date can be made optional using this setting from V5 onwards: 
<img width="1116" alt="CleanShot 2022-02-05 at 16 34 14@2x" src="https://user-images.githubusercontent.com/8002555/152639450-ba169700-11ee-40d6-b182-6b27a6763e16.png">
