### ISSUE TITLE
Display invoice amount under invoice listing

### ISSUE THREAD

**Issue by imchivaa** [crater-invoice/crater#507]
**Is your feature request related to a problem? Please describe.**
When an invoice is fully paid, viewing the invoice listing shows amount due is 0.00 but need to view the invoice to know the actual amount of the invoice. 

**Describe the solution you'd like**
Display invoice actual amount under invoice listing.

**Describe alternatives you've considered**
Provide an option to display the invoice actual amount or a way to extend by code to have it without breaking the update feature were it get overwritten once updated to latest version.

Currently using version: 4.2.0

**Comment by imchivaa** [comment]
Cool, is there any plan in the future to customize the listing? Like displaying custom field result. 
Example: I added a custom field (switch toggle) to invoice called delivered to indicate order is delivered to customer or not. If can customize to the listing will be great, i don't mind if code need to be changed but worry overwrite/upgrade issue later due to merging.

**Comment by mohitpanjwani** [comment]
> Cool, is there any plan in the future to customize the listing? Like displaying custom field result.
> Example: I added a custom field (switch toggle) to invoice called delivered to indicate order is delivered to customer or not. If can customize to the listing will be great, i don't mind if code need to be changed but worry overwrite/upgrade issue later due to merging.

Hey man, you could customise it yourself but it will definitely get overridden in the update. 

I don’t see a way to do this without having to fix this manually  when a new update comes in. 

What might make more sense is the ability to select the columns on the table according to requirements but its pretty complicated. But I really like this idea as it will allow so many more possibilities when combined with custom fields.  

We will be definitely adding this in a future update but not sure when. For now I will add this feature to the Roadmap.

**Comment by mohitpanjwani** [comment]
Added Total column on Listings page in V5 👍 

<img width="1032" alt="CleanShot 2021-12-06 at 14 31 58@2x" src="https://user-images.githubusercontent.com/8002555/144817575-42f5b50a-ebce-4e28-a10e-8d034df28dff.png">
