### ISSUE TITLE
Limit time to view invoices online for GDPR compliance 

### ISSUE THREAD

**Issue by Pazekal90** [crater-invoice/crater#522]
The time a invoice pdf is viewable should be limited. Maybe after setting the invoice to paid is a good option to not let the invoice publicly available.

Alternatively a specified time after invoice creation the invoice should not be available for download anymore. 

In Germany for example this is a critical feature to not let personal data rest online and available(even behind a cryptic link) forever after.

**Comment by BaxAndrei** [comment]
In the future, it may be accessible only to the customer to whom the invoice / payment / estimate belongs through the portal. I saw that it was planned to be added.

**Comment by mohitpanjwani** [comment]
Completely agree with you! We're adding an option to fix this. 

The default will be what it is right now but it will be configurable from settings.

**Comment by mohitpanjwani** [comment]
Released on V6: 
<img width="1768" alt="CleanShot 2022-02-05 at 16 30 29@2x" src="https://user-images.githubusercontent.com/8002555/152639336-9d578f2f-0460-45c1-9034-7b0f75e15938.png">
