### ISSUE TITLE
Add Debounce to fetchData() on table filters

### ISSUE THREAD

**Issue by DevOptum12** [crater-invoice/crater#527]
**Is your feature request related to a problem? Please describe.**
When using the filter to search the table data the database is queried once on each key input. This puts heavy load on the server when a user is typing in the search filter.

**Describe the solution you'd like**
Can a debounce function be used to only run a query every n seconds or when user is done typing. Additionally we could implement algolia search?

**Comment by mohitpanjwani** [comment]
Agreed! We're already working on this (not algolia but a basic debounce filter should do it for now)

**Comment by mohitpanjwani** [comment]
Implemented debounce on V5 👍
