### ISSUE TITLE
Send Estimate: Something Went Wrong

### ISSUE THREAD

**Issue by NathanHawke** [crater-invoice/crater#531]
Whenever I try to send an estimate I get a red popup in the top right that says "Something Went Wrong"

I've checked my Apache error and access logs, the Crater log folder, and the browser console. The only error I can find is in the browser console "Uncaught (in promise) TypeError: e.showNotification is not a function"

- Crater version: 4.2.0
- PHP version: 7.4.3
- Database type and version: MySQL 8.0.26
- OS:  Ubuntu 20.04.2
- Browser: Firefox

**Comment by mwikala** [comment]
As there is a new major version, I'd recommend you try and update your installation to v5.0.3 (the latest as of writing this). If the issue is persistent then feel free to reopen this issue.
