### ISSUE TITLE
Support for multiple currencies in the dashboard

### ISSUE THREAD

**Issue by BaxAndrei** [crater-invoice/crater#534]
**Is your feature request related to a problem? Please describe.**
Support for multiple currencies in the dashboard and to be able to switch between them using buttons.
At the moment, I have several currencies, and on the main page I see the result in the main currency combined with all the other currencies as if they were one and the same. ([dashboard total](https://user-images.githubusercontent.com/12484505/128645219-41cdbe98-4c64-4322-ab79-6e657dbf4c20.png), [due invoices and their values and currencies](https://user-images.githubusercontent.com/12484505/128645251-6e953c05-1307-4454-b3ae-686a9727cf92.png))

**Describe the solution you'd like**
I hope this fits there: [image](https://user-images.githubusercontent.com/12484505/128645188-75c4f037-bbd5-4ee1-a6da-862fced43f5e.png)

**Describe alternatives you've considered**
The possibility of adding an exchange rate for each currency with reference to the main one would be useful.

**Comment by b4allb4u** [comment]
If possible, please add an option of credit limit to the customers at the time of customer creation.

**B4ALLB4U**

**Comment by azaricstefan** [comment]
This is really important feature request.

**Comment by BaxAndrei** [comment]
I checked, and the amount is combined as main currency everywhere (regardless of currency). Reports, customer status, home page, etc.

**Comment by BaxAndrei** [comment]
From what I noticed, it was added in version 5.0. Thanks.
