### ISSUE TITLE
Converting an estimate to an invoice should delete the estimate

### ISSUE THREAD

**Issue by SteveEdson** [crater-invoice/crater#539]
**Is your feature request related to a problem? Please describe.**
Currently, when converting an estimate to an invoice from the context menu, it redirects you to the new invoice. I can then make any alterations and send it to the client. I assume that the estimate is now gone, since it as been converted. If I forget to manually delete the estimate afterwards, I often come back to the estimates and wonder if I've invoiced it already, resulting in having to try and find the matching invoice.

**Describe the solution you'd like**
Delete the estimate on save of the new invoice, or prompt to delete the estimate afterwards.

**Describe alternatives you've considered**
Rename the "convert to invoice" to not use the word "convert", since this implies that it will be changed. 

Something like "create an invoice from estimate", however this isn't ideal either for the reasons mentioned above.

Thanks!

**Comment by SteveEdson** [comment]
Does one of the following work as a solution? Could maybe be a setting:

- Marked as accepted after converting
- Delete after converting
- Ask the user each time
- Leave as is

**Comment by azaricstefan** [comment]
@SteveEdson great idea!

Let's include @mohitpanjwani in the discussion. What's your opinion?

1. Marked as accepted after converting
2. Delete after converting
3. Ask the user each time
4. Leave as is

Option 1 could be configurable in settings
Option 2 could be configurable in settings
Option 3 could be configurable in settings
Option 4 [default behavior, to be backwards compatible]

**Comment by mohitpanjwani** [comment]
I love the suggestions @SteveEdson and @azaricstefan. We'll implement this as a setting 👌 

I would personally use the `Marked as accepted` one but a configurable setting will allow all the possibilities!

**Comment by mohitpanjwani** [comment]
<img width="730" alt="CleanShot 2021-12-06 at 14 26 41@2x" src="https://user-images.githubusercontent.com/8002555/144816766-b3531b77-945c-4aea-831d-404776977fec.png">

Added the option on V5 as discussed. 

You can find it on Settings -> Customization -> Estimates tab.

**Comment by SteveEdson** [comment]
Excellent, thanks!
