### ISSUE TITLE
add existing payments to invoice

### ISSUE THREAD

**Issue by maltegrosse** [crater-invoice/crater#547]
as I can enter payments for customer by keeping a blank invoice number, it would be great to later attach these payments once I created an invoice. is this somehow possible?

**Comment by mohitpanjwani** [comment]
> ts for customer by keeping a blank invoice number, it would be great to later attach these payments once I created an invoice. is this somehow possible?

Hey there, I don't see why that would be an issue? 

Have you encountered any issue with creating a payment without invoice selected and then later editing the same payment with your actual invoice?

**Comment by maltegrosse** [comment]
The customer and invoice field is grayed out (disabled) once you want to edit a payment. All other fields can be edited.

**Comment by mohitpanjwani** [comment]
Oh I see. Yeah that’s an issue. Thanks for letting me know. 

We will check that out.

**Comment by mohitpanjwani** [comment]
Issue has been fixed on v5.

Please update from Settings -> Update App.

Please reopen the issue if you still encounter this.
