### ISSUE TITLE
Currency symbol on wrong side of number in admin area

### ISSUE THREAD

**Issue by PDylan93** [crater-invoice/crater#568]
I recently upgraded (manually due to automatic update issues) from version 3.11 to 4.2.0 and now the currency symbol appears on the wrong side of the numbers across the admin area. This doesn't seem to affect PDFs. I've tried setting my currency to others (and then back to GBP) but the issue persists.

Screenshot: https://i.ibb.co/ZBXKswx/issue-example.png

- Crater version: 4.2.0
- PHP version: 7.4

**Optional info**
- OS:  Windows 10
- Browser: Google Chrome

**Comment by mohitpanjwani** [comment]
Issue has been fixed on v5.

Please update from Settings -> Update App.

Please reopen the issue if you still encounter this.
