### ISSUE TITLE
problem limit characters on description

### ISSUE THREAD

**Issue by leonardotandoi** [crater-invoice/crater#570]
**Describe the bug**
When i put into an estimate a lot of information, the system report me there are limit of 255 characters. It's possible to increase a number of characters on db?

**Screenshots**
https://ibb.co/q1xPPcg

**Please complete the following information:**
- Crater version: 4.2.0
- PHP version: 7.4
- Database type and version: MySQL 8.0.25

**Comment by DeanKamitsis** [comment]
Don't forget this needs updating in the EstimatesRequest file too.

**Comment by mohitpanjwani** [comment]
Issue has been fixed on v5.

Please update from Settings -> Update App.

Please reopen the issue if you still encounter this.
