### ISSUE TITLE
Edit customer modal always shows "invalid email"

### ISSUE THREAD

**Issue by davwheat** [crater-invoice/crater#585]
**Describe the bug**
If you are creating an invoice, and choose to edit a customer while doing so, updating the email field always reports "invalid email", even for correct emails.

Copying the email out of the field, closing the modal, reopening the modal and pasting it in results in no problems.

**Screenshots**
![image](https://user-images.githubusercontent.com/7406822/138570727-a1a81c5c-2d58-4ed0-afd7-9e62a17e9916.png)

**Comment by mohitpanjwani** [comment]
Issue has been fixed on v5.

Please update from Settings -> Update App.
