### ISSUE TITLE
Bug: Add Payment Page - + Insert Note

### ISSUE THREAD

**Issue by DeanKamitsis** [crater-invoice/crater#590]
The “+ Insert Note” button to select a saved note doesn’t work

**Comment by DeanKamitsis** [comment]
Seems to be fixed in the master branch.

**Comment by mohitpanjwani** [comment]
> Seems to be fixed in the master branch, although now the link shows on top of the Payment Mode drop-down when it is open.

Dropdown issues are fixed on next release. 

Should be available in next 2 weeks. We have recreated the whole frontend using Vue 3 + HeadlessUI.

**Comment by mohitpanjwani** [comment]
Issue has been fixed on v5.

Please update from Settings -> Update App.

Please reopen the issue if you still encounter this.
