### ISSUE TITLE
When customer clicks link in email to view invoice, first load gets a 500 Server Error

### ISSUE THREAD

**Issue by jakeparis** [crater-invoice/crater#591]
**Describe the bug**
When customer clicks link in email to view invoice, first load gets a 500 Server Error. When reloading the page, the pdf comes up. Closing the tab and reclicking the link in the email brings up the PDF with no problems, it seems to be just from that first load. Perhaps it has something to do with the invoice view tracking? 

In my case, the customer didn't know to reload, so they complained about the 500 Error, but Crater says they viewed the invoice. 

**Expected behavior**
They can see the PDF the first time.

**Please complete the following information:**
- Crater version: 4.2.0
- PHP version: 7.4.x
- Database type and version: mysql

**Comment by DeanKamitsis** [comment]
I am also experiencing this issue.

**Comment by DeanKamitsis** [comment]
I found out what's causing it for me - I'm using SMTP as my mailer.
Crater tries to set the customer's email address as the sender but SMTP is blocking it so throws the error message.

**Comment by mohitpanjwani** [comment]
> I found out what's causing it for me - I'm using SMTP as my mailer.
> Crater tries to set the customer's email address as the sender but SMTP is blocking it so throws the error message.

Yes that must be it.

 If you haven’t configured an email provider then you can disable the viewed notifications from settings page. 

That would fix it.

**Comment by DeanKamitsis** [comment]
Please reopen - smtp is configured which is why it throws the error as the sender is set to the customers email address which smtp throws the error.

**Comment by mohitpanjwani** [comment]
> Please reopen - smtp is configured which is why it throws the error as the sender is set to the customers email address which smtp throws the error.

oh right! That would never work. 

Thanks for the clarification. We'll deploy a fix for this.

**Comment by marvelefe** [comment]
Please any update on this? Experiencing the same issue.

**Comment by mohitpanjwani** [comment]
This should no longer be an issue on v5. Please update from Settings -> Update App. 

You can reopen this issue if you can still reproduce this on v5.
