### ISSUE TITLE
Custom Date field not retaining selected date

### ISSUE THREAD

**Issue by kevdagoat** [crater-invoice/crater#593]
**Describe the bug**
Custom date field for invoice does not save the selected date to the database when creating a new invoice and subsequently forgets it when generating a PDF of the invoice (and even displaying the edit invoice panel).

**Expected behavior**
Date selection is remembered and is rendered into the invoice correctly.

**Screenshots**
Field settings:
![image](https://user-images.githubusercontent.com/42062334/140021622-6297eeac-709b-4a6f-be8c-f9c469b4f911.png)

Date selector showing selected date:
![image](https://user-images.githubusercontent.com/42062334/140021917-80bde29d-1fd9-45d9-b351-9a7095abc2b2.png)

Editing the invoice results in the date not showing up anymore:
![image](https://user-images.githubusercontent.com/42062334/140021995-626e4575-35c5-48f1-8c92-858c57c13751.png)

Database shows that the custom fields were not saved, manually adding the date results in everything working as intended.
![image](https://user-images.githubusercontent.com/42062334/140022593-3ce5c5de-5a01-4986-a5a4-c58c87967f82.png)

**Please complete the following information:**
- Crater version: 4.2.0
- PHP version: 7.4.3
- Database type and version: 10.5.10-MariaDB-1:10.5.10+maria~focal

**Optional info**
- OS:  Ubuntu 20.04 LXC Container
- Browser: Firefox 94.0
- I am using a custom invoice template, but the issue existed before I created the template (and exists with default templates).
- I have not looked at the date time field type but all other field types, string, bool, etc work as intended.

Awesome app by the way, highly recommended!!!!

**Comment by mohitpanjwani** [comment]
Hey man! 

Thanks for the report but I just rechecked this and it seems to work as expected in v5. 

Please reopen the issue if you still encounter this.

**Comment by kevdagoat** [comment]
Cool, I’ll try it and reopen if it doesn’t work. Thanks again!
