### ISSUE TITLE
Cannot make it past onboarding step 3

### ISSUE THREAD

**Issue by vonroga** [crater-invoice/crater#598]
**Describe the bug**
I've tried so hard to get this to work, following your instructions. My best guess is that it has something to do with line 172 in crater\app\Space\EnvironmentManager.php where `getPdo()` is undefined, but I honestly have no idea.

**Expected behavior**
I'd expect to make it through the setup without issues. Clearer instructions wouldn't hurt. There is a lot lacking from your documentation: [Developer Guide](https://docs.craterapp.com/developer-guide.html)

**Screenshots**
![image](https://user-images.githubusercontent.com/61405141/142279486-51101514-6ddc-4bb5-ad34-9554d2520410.png)

![image](https://user-images.githubusercontent.com/61405141/142279451-41537856-6b91-474d-a93c-a0d288df6969.png)

![image](https://user-images.githubusercontent.com/61405141/142279960-bbb5eca0-5dc8-4812-904b-663b55135cb7.png)

**Please complete the following information:**
- Crater version: cloned from repo today
- PHP version: 
- Database type and version: mysql

**Optional info**
- OS:  windows 10
- Browser: chrome

**Comment by abhishek1234graphs** [comment]
I am also facing an incomprehensible error. The migration abruptly stops. The following tables have been created but then the migration process halts suddenly.
<img width="760" alt="Migration Problem" src="https://user-images.githubusercontent.com/21076963/142574306-cec1c207-7b5b-4142-af0c-d5a1fd272b66.png">

You might argue that my Database connection was not proper - but then surprisingly, how were the above tables created? 

This is the JSON error returned during Step 3 of Onboarding
`"message": "SQLSTATE[HY000] [2002] Connection refused (SQL: alter table `users` add unique `users_email_unique`(`email`))",`


Could anyone please explain?

**Comment by korirdennis** [comment]
I am also getting an error at stage 3 
![image](https://user-images.githubusercontent.com/38191858/142705136-f8e0475c-58b9-43c8-9d15-e4533eea7a57.png)

you assistance will be highly appreciated

**Comment by samehdoush** [comment]
I am also getting an error at stage 3

![image](https://user-images.githubusercontent.com/48515888/142911095-458e3873-c018-45b1-99ca-7945c75204b4.png)

**Comment by samehdoush** [comment]
@korirdennis 
in app / Space / RequirementsChecker.php
function getMysqlVersionInfo replace to 

![image](https://user-images.githubusercontent.com/48515888/142915376-4b7dfd6e-fd42-47ac-b010-3e58bdbdb3ce.png)

**Comment by mohitpanjwani** [comment]
Please try the solution by @samehdoush. 

We're looking into removing this requirement checker completely in release: 5.1. 

Also can you please mention your current mysql version? I feel like the error you're getting might be related to using an older version of mysql.

**Comment by savan1012** [comment]
@mohitpanjwani Sir,
i am also try solution by @samehdoush.
but it show mysqli minimum version required 10.0.0 
otherwise it display migration error on on_bording

**Comment by vonroga** [comment]
@mohitpanjwani
`mysql  Ver 15.1 Distrib 10.4.21-MariaDB, for Win64 (AMD64), source revision 4902b0fdc91cc6dc169dd2322daf966a2eeafdd8`

**Comment by vonroga** [comment]
@mohitpanjwani
So, we used composer to install the project instead of NPM and it seems to work fine. 🤷‍♂️

**Comment by mohitpanjwani** [comment]
> @mohitpanjwani So, we used composer to install the project instead of cloning the repository and it seems to work fine. 🤷‍♂️ On that note, I must reiterate that the steps for developers are NOT up to date or complete. More information is required.

Hey @vonroga, Glad to know that you managed to fix it. Sorry I was a little busy with v5, so couldnt get back to you earlier. 

If you find any issues on v5, then feel free to discuss on discord or create a github issue. Closing this for now 👍
