### ISSUE TITLE
dropdown is trasparent

### ISSUE THREAD

**Issue by simon1tan** [crater-invoice/crater#605]
Firefox 87

On https://demo.craterapp.com/admin/items/5/edit, the dropdown is transparent, background components show through, making values unreadable.

**Expected behavior**
Dropdown should not be transparent

**Comment by mohitpanjwani** [comment]
> Firefox 87
> 
> On https://demo.craterapp.com/admin/items/5/edit, the dropdown is transparent, background components show through, making values unreadable.
> 
> **Expected behavior** Dropdown should not be transparent

Seems to work perfectly for me on my firefox browser. 

Can you post a screenshot and the version of your browser?
