### ISSUE TITLE
Unauthenticated error after upgrading to 5.0

### ISSUE THREAD

**Issue by vbezruchkin** [crater-invoice/crater#606]
First of all, thanks for the update with new features. They look awesome. 

After upgrading from 4.2 I can see a login screen without any problem. Once I input my details, I'm logged in but I can only see aviation loading without any progress.

When I open debug console, I could see the following:

![image](https://user-images.githubusercontent.com/2760455/144155853-3bd6b095-ff95-4f87-8c44-e479465752be.png)

The requirements are fine. We have PHP 7.4. MySQL 8.0. Server version is CentOS.

Any ideas? Thanks in advance.

**Comment by vbezruchkin** [comment]
I'm not sure if it can help, but here is one more thing I see when I try to restore my password:

```
{message: "CSRF token mismatch.", exception: "Symfony\Component\HttpKernel\Exception\HttpException",…}
exception: "Symfony\\Component\\HttpKernel\\Exception\\HttpException"
file: "/home/XXX/app/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php"
line: 389
message: "CSRF token mismatch."
```

But my .env variables are configured to the domain I use.

**Comment by vbezruchkin** [comment]
Resolved. I just had to add trusted proxies. Cheers

Thanks

**Comment by adampatterson** [comment]
@vbezruchkin How did you update trusted proxies?

I am having the same issue.

**Comment by cgx** [comment]
Make sure to that all [environment variables](https://docs.craterapp.com/upgrade-guide.html#using-auto-installer) have been configured, especially `SANCTUM_STATEFUL_DOMAINS` and `SESSION_DOMAIN`.
