### ISSUE TITLE
Translations for new features in 5.0.0 missing

### ISSUE THREAD

**Issue by waschinski** [crater-invoice/crater#608]
**Describe the bug**
Crater is basically showing all new features in English only when set to a different language e.g, German. On Crowdin status of German translation is being shown as 99% though.

**Expected behavior**
Text showing in German or at least new strings available to localize in Crowdin.

**Please complete the following information:**
- Crater version: 5.0.1

**Comment by mohitpanjwani** [comment]
> **Describe the bug** Crater is basically showing all new features in English only when set to a different language e.g, German. On Crowdin status of German translation is being shown as 99% though.
> 
> **Expected behavior** Text showing in German or at least new strings available to localize in Crowdin.
> 
> **Please complete the following information:**
> 
> * Crater version: 5.0.1

Yes the translation file will be updated tomorrow. 

As soon as the contributions are available, we will release updates to fix this .

**Comment by waschinski** [comment]
Missing translation is now available on Crowdin, thanks!
