### ISSUE TITLE
Adding Payment for Invoice doesn't use the actual invoiced value

### ISSUE THREAD

**Issue by Pazekal90** [crater-invoice/crater#609]
Adding Payment for Invoice doesn't use the actual invoiced value

Invoice value is 19,50 € but when adding a payment it shows me 1 € as standard. I have to manually adjust this to the invoice value. That was better in the 4.2.0 version. 

<img width="1296" alt="image" src="https://user-images.githubusercontent.com/25208775/144310246-0dff2e8d-a03f-4b50-8be6-4d871794b053.png">

**Comment by mohitpanjwani** [comment]
> Adding Payment for Invoice doesn't use the actual invoiced value
> 
> Invoice value is 19,50 € but when adding a payment it shows me 1 € as standard. I have to manually adjust this to the invoice value. That was better in the 4.2.0 version.
> 
> <img alt="image" width="1296" src="https://user-images.githubusercontent.com/25208775/144310246-0dff2e8d-a03f-4b50-8be6-4d871794b053.png">

Did you deselect the customer? I just reviewed this and it perfectly changes the amount to the due_amount of the invoice.

**Comment by Pazekal90** [comment]
Your fix works. Thanks. Tested with 5.0.2
