### ISSUE TITLE
Completed invoices still in the list of due invoices 

### ISSUE THREAD

**Issue by Pazekal90** [crater-invoice/crater#611]
**Describe the bug**
After completing some invoices(in the list of invoices they are marked as completed) those invoices are still in the list of due invoices even there is no payment open on those. 

**Expected behavior**
They should not be displayed anymore. 

**Screenshots**
<img width="779" alt="image" src="https://user-images.githubusercontent.com/25208775/144311843-9a50408e-8c30-4e94-b10f-0251d4f82ea4.png">

**Please complete the following information:**
- Crater version: 5.0.2
- PHP version: 8.0
- Database type and version: mysql

**Comment by mohitpanjwani** [comment]
Thanks a lot for the quick report! 

There's an issue with `base_due_amount` not calculating on invoice/payment crud. Just fixed it + added the migration so it will fix this issue + the other issue you mentioned regarding wrong due amount.

**Comment by Pazekal90** [comment]
Works perfect. Thanks
