### ISSUE TITLE
DockerCompose Failed 5.0.2

### ISSUE THREAD

**Issue by MaximeDemurger** [crater-invoice/crater#615]
**Describe the bug**
I try to compose up the last version of crater (5.0.2) and get an error

**Expected behavior**
to build crater

**Screenshots**
![Screenshot 2021-12-02 at 15 43 07](https://user-images.githubusercontent.com/60433883/144443931-cd793b9f-d7e7-4a55-ae6d-30960c7bffed.png)

**Please complete the following information:**
- Crater version: 5.0.2
- PHP version: 7.4
- Database type and version: mariadb 10.3.31

**Optional info**
- OS: UBUNTU 20.04
- Browser: safari

**Comment by mohitpanjwani** [comment]
Hey guys, this should no longer be an issue on https://github.com/crater-invoice/crater/releases/tag/5.0.3

Please pull the changes again and run `docker-compose up --build` again. 

Oh and I've changed the nginx port back to `80` as it was in v4. Please make sure to check accordingly when you're testing. 

Let me know if this still an issue. Thank you for your patience :)

**Comment by mohitpanjwani** [comment]
Closing this as its fixed but please reopen if you still encounter this.
