### ISSUE TITLE
Create SECURITY.md

### ISSUE THREAD

**Issue by JamieSlome** [crater-invoice/crater#621]
Hey there!

I belong to an open source security research community, and a member (@theworstcomrade) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by DeanKamitsis** [comment]
If you don’t hear back, try them on info@craterapp.com - they’ve also got a twitter and facebook account (username craterapp)

**Comment by mohitpanjwani** [comment]
> Hey there!
> 
> I belong to an open source security research community, and a member (@theWorstComrade) has found an issue, but doesn’t know the best way to disclose it.
> 
> If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.
> 
> Thank you for your consideration, and I look forward to hearing from you!
> 
> (cc @huntr-helper)

Hey there! 

Thank you for the reminder. I received the notification from huntr regarding this but we were in the middle of a major release. Hopefully this won’t be an issue on this version but I’ll review it today 👍

Also I’ll add the security file.

**Comment by mohitpanjwani** [comment]
I've added the file as mentioned & also responded on huntr regarding the vulnerability. 


https://github.com/crater-invoice/crater/blob/master/SECURITY.md
