### ISSUE TITLE
SQLSTATE [HY000][2002] connection refused

### ISSUE THREAD

**Issue by shahidak7** [crater-invoice/crater#622]
Hi there.. I am trying to install the newer version on my IONOS hosting service. I followed the instructions for the manual install. However during the installation at the database step i keep getting this error SQLSTATE [HY000][2002] connection refused.

It was working fine with the older version. This is a complete new install.  Below is the screenshot of the error. I would appreciate i anyone can help me with this. I tried going through the previous sql errors from the Issues but i couldn't find a fix.
![Screen Shot 2021-12-05 at 10 59 13 AM](https://user-images.githubusercontent.com/47109213/144735098-59f4cf5b-8e3a-4bb5-af40-20689368d4d4.png)

**Comment by tsdevelopment** [comment]
In my opinion your database host must be wrong. IONOS uses something like "db.ionos.com".

**Comment by mohitpanjwani** [comment]
Closing this as this is a server configuration issue. Your host is definitely incorrect I think. 

Please feel free to reopen if you find that there's an issue with Crater.
