### ISSUE TITLE
update command line ::  php artisan crater:update

### ISSUE THREAD

**Issue by michelmelo** [crater-invoice/crater#633]
**Describe the bug**
Your currently installed version is 4.2.0

Checking for update...
✅ exif
✅ pdo
✅ bcmath
✅ openssl
✅ mbstring
✅ json
✅ xml
✅ fileinfo
✅ php(7.4)

 Do you wish to update to 5.0.1? (yes/no) [no]:
 > yes

Downloading update...
Unzipping update package...
Copying update files...
Deleting unused old files...
Running Migrations...
SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'prefix' (SQL: alter table `customers` add `prefix` varchar(255) null after `id`)

**Comment by mohitpanjwani** [comment]
> **Describe the bug** Your currently installed version is 4.2.0
> 
> Checking for update... ✅ exif ✅ pdo ✅ bcmath ✅ openssl ✅ mbstring ✅ json ✅ xml ✅ fileinfo ✅ php(7.4)
> 
> Do you wish to update to 5.0.1? (yes/no) [no]:
> 
> > yes
> 
> Downloading update... Unzipping update package... Copying update files... Deleting unused old files... Running Migrations... SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'prefix' (SQL: alter table `customers` add `prefix` varchar(255) null after `id`)

Did you run the migrations previously? And did it fail? 

The prefix was added in a recent update so it looks like that specific migration is trying to run again and causing issue. 

Please take a backup and then delete the prefix column. Try running the migrate command again to see if that fixes it.

**Comment by mohitpanjwani** [comment]
Hey @michelmelo, 

We've just fixed most of issues with updates on 5.0.5. 

You can just do a `git pull` with the latest code of Crater and run `php artisan migrate`. That should fix everything. 

If you don't use git, then you can just copy all the latest files from Crater 5.0.5 zip file.

-------------------

You can also update from Settings -> Update App again if you have the old version backup.

**Comment by mohitpanjwani** [comment]
I’m closing this issue but please feel free to re-open if you get any more errors on update.

Also if you’re stuck on the old update because of any of the above mentioned errors, please send a dm on discord. I’ll help you fix it personally 👍
