### ISSUE TITLE
Custom Fields are not working with Expenses

### ISSUE THREAD

**Issue by dwyer125** [crater-invoice/crater#638]
**Describe the bug**
The custom fields are showing on the Expense page.
But when adding an Expense, the expense says it was added but the custom field data is not saved. 
Checked database and there is nothing added to the custom_field_values table

**Expected behavior**
Added expenses should save custom field data

**Please complete the following information:**
- Crater version: 5.0.4
- Database type and version: mysql

**Optional info**
- OS:  Docker on Ubuntu
- Browser: Chrome

**Comment by mohitpanjwani** [comment]
Fixed in https://github.com/crater-invoice/crater/releases/tag/5.0.5

Thanks for the report 👍

**Comment by tamsir** [comment]
Hello,
Is It possible to get the value of each custom_field_values directly in the invoice.blade.php
Thanks for help
