### ISSUE TITLE
Pages that do not follow the date formatting settings

### ISSUE THREAD

**Issue by BaxAndrei** [crater-invoice/crater#648]
**Describe the bug**
Although I set a date format (dd.mm.yyyy) on some pages (I will attach below) it shows a completely different format (yyyy-mm-dd).
Pages: 
- /admin/expenses
- /admin/payments
- /admin/payments/{X}/view

**Expected behavior**
Display the date format as the rest of the pages

**Screenshots**
![image](https://user-images.githubusercontent.com/12484505/145678525-0e609f02-738a-4883-956a-1ea88548a159.png)
![image](https://user-images.githubusercontent.com/12484505/145678530-a58dfeaf-0cee-48f4-961c-7b695ba8134e.png)
![image](https://user-images.githubusercontent.com/12484505/145678582-a45d1df4-ede4-4d70-a55c-48357e396ee9.png)

**Please complete the following information:**
- Crater version: 5.0.4
- PHP version: 7.4.26
- Database type and version: 5.7.34 - MySQL Community Server (GPL)

**Optional info**
- OS:  Windows 11 21H1
- Browser: Google Chrome | 96.0.4664.45 (Official Build) (64-bit)

**Comment by mohitpanjwani** [comment]
> 

right! yeah this is an issue. Thanks for the feedback.

**Comment by BaxAndrei** [comment]
> > 
> 
> right! yeah this is an issue. Thanks for the feedback.

The bug is no longer present in the latest version. Thank You!
