### ISSUE TITLE
404 Error 

### ISSUE THREAD

**Issue by ncamacho97** [crater-invoice/crater#650]
i get 404 error i have .htaccess cant get the install wizard

**Comment by ncamacho97** [comment]
ive tried using cyberpanel no luck im on cpanel still no luck

**Comment by BaxAndrei** [comment]
Is the script installed on a subdomain or subdirectory?

**Comment by ncamacho97** [comment]
its on a sub dir

**Comment by ncamacho97** [comment]
ill try hey man i wasn't expecting that fast of response thanks

**Comment by ncamacho97** [comment]
``<IfModule mod_rewrite.c>
    <IfModule mod_negotiation.c>
        Options -MultiViews -Indexes
    </IfModule>

    RewriteBase /subdirectory/
    Options +FollowSymLinks
    RewriteEngine On

    # Handle Authorization Header
    RewriteCond %{HTTP:Authorization} .
    RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]

    # Redirect Trailing Slashes If Not A Folder...
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_URI} (.+)/$
    RewriteRule ^ %1 [L,R=301]

    # Send Requests To Front Controller...
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^ index.php [L]
</IfModule> 
``
still no affect :(

**Comment by ncamacho97** [comment]
@BaxAndrei

**Comment by mohitpanjwani** [comment]
Hey @ncamacho97, Did you select the `crater/public` folder as the root folder when adding the subdomain? 

Also please use the pull-request template which asks you for information regarding your server and other details.

**Comment by mohitpanjwani** [comment]
https://github.com/crater-invoice/crater/issues/655#issuecomment-993362711

I think it might be related. Make sure check this one out ☝️

**Comment by mohitpanjwani** [comment]
Closing this but feel free to reopen if you're still stuck @ncamacho97

**Comment by 161134077** [comment]
create file .htaccess

RewriteEngine On

RewriteCond %{HTTP:Authorization} ^(.+)$
RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]

RewriteCond %{REQUEST_FILENAME} -d [OR]
RewriteCond %{REQUEST_FILENAME} -f
RewriteRule ^ ^$1 [N]

RewriteCond %{REQUEST_URI} (\.\w+$) [NC]
RewriteRule ^(.*)$ public/$1

RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule ^ server.php
