### ISSUE TITLE
More Backup Locations

### ISSUE THREAD

**Issue by DiscoverSquishy** [crater-invoice/crater#672]
**Is your feature request related to a problem? Please describe.**
Currently Crater only supports same-server backups.

**Describe the solution you'd like**
Ability to schedule backups to certain locations, with options to backup type.
Ability to use SFTP, FTP and S3 for manual and/or scheduled backup.

**Documentation Note**
Once this is added, it would be good if https://docs.craterapp.com/guide/backups.html#create-a-new-backup was updated with the new detail. Along if you can also emphasize on the differences of local_public and local_private on the docs as well.

**Comment by jpmurray** [comment]
You can already (manually) backup to any S3 compatible storage !
