### ISSUE TITLE
Issues updating from 3.2 - 4/5

### ISSUE THREAD

**Issue by adampatterson** [crater-invoice/crater#674]
**Describe the bug**
At various times during the update I encounter issues with missing providers and Passport is missing.

One of the migrations hit a Doctrine error that prevented me from going forward as some of the migrations were applied.

At one point after clearing caches, deleting the vendor folder everything installed but my login would show that it was successful then redirect me back saying unauthenticated or unauthorized ( I forget which one it was ).

I cleared browser cookies/session/localstorage.  I tried resetting my password without any luck.

I have tried 4 or 5 times to update and have not had any luck.

I will be attempting to move my live install locally where I can better test the process.

**Expected behavior**
I'd live to run the `crater:update` command and be done.

**Please complete the following information:**
- Crater version:  3.2.0
- PHP version: 7.4.9
- Database type and version:  MySql

**Optional info**
- OS:  Ubuntu 18 I think
- Browser: Chrome

**Comment by mohitpanjwani** [comment]
https://docs.craterapp.com/upgrade-guide.html

Hey @adampatterson,
Did you follow this guide for upgrading to version 4? 

After that it should be pretty simple to upgrade to version 5.

**Comment by adampatterson** [comment]
Hello @mohitpanjwani.

I have, I followed the non-docker instructions.

I ran the first command twice, and on the `composer:update` step began to get the errors.  After clearing the caches and removing the vendor folder it seemed to work but the migrations then caused problems.

**Comment by mohitpanjwani** [comment]
Sorry for the trouble. 

Can you please dm me on discord? We can run the update once more together and solve any potential issues right away.

**Comment by adampatterson** [comment]
Thanks @mohitpanjwani 

I will try to send you a DM after the holidays.

Locally I installed 5 and then manually migrated my data from 3.2 over and it seems to be working.

I will be testing on my server just to confirm that it's working properly.


Cheers!

**Comment by mohitpanjwani** [comment]
Thanks @adampatterson. I hope you've resolved the issue. 

Please feel free to reopen the issue or DM me if there's anything else.
