### ISSUE TITLE
My phone number shows in customer area in estimate

### ISSUE THREAD

**Issue by jakeparis** [crater-invoice/crater#693]
I created a customer, and gave them a phone number in both the "billing address" and "basic information" section. I then created an "Estimate" for that customer. When I view the embedded pdf, _my_ phone number shows up next to the customer's contact information.

**Comment by mohitpanjwani** [comment]
> 

Sorry I didn't get it. 

Why would you add your phone number on customer's billing address? 

& Can you show me where exactly it shows your phone number using a screenshot?

**Comment by jakeparis** [comment]
Here's a screenshot. _My_ phone number shows in the client section:
![Screen Shot 2022-01-05 at 8 39 29 AM](https://user-images.githubusercontent.com/7408985/148227989-7df2c032-2cb3-4dc7-8dc5-98542598c9db.jpg)

**Comment by mohitpanjwani** [comment]
Have you made any changes to default format of your billing address on Settings -> Customization -> Estimates: 
<img width="352" alt="CleanShot 2022-01-12 at 15 18 18@2x" src="https://user-images.githubusercontent.com/8002555/149115971-17a3b6f2-b625-42e6-a820-30cb4fac9752.png">

**Comment by jakeparis** [comment]
You are right! I accidentally had `{COMPANY_PHONE}` instead of `{BILLING_PHONE}` in the customer's billing address format area. Thank you!
