### ISSUE TITLE
Driver Error (mysql & postgres)

### ISSUE THREAD

**Issue by RevRebel** [crater-invoice/crater#697]
**Describe the bug**
When installing from the provided steps, error accuse on the setup screen for databases. When using the mysql option the error occurs, then when choose postgres you simply get the error no driver found.

Error
could not find driver (SQL: select * from information_schema.tables where table_schema = public and table_name = abilities and table_type = 'BASE TABLE')

**Please complete the following information:**
- Crater version: 5
- PHP version:  7.4.27
- Database type and version: MariaDB 1:10.6.5+Maria~focal (from your docker repo) & tried with Postgres 14.1-1.pgdg110+1

**Optional info**
- OS:  Docker on Ubuntu 20.4 Server
- Browser: Safari & Chrome

**Comment by RevRebel** [comment]
Adding Stack Trace 

     * @throws \Illuminate\Database\QueryException
     */
    protected function runQueryCallback($query, $bindings, Closure $callback)
    {
        // To execute the statement, we'll simply call the callback, which will actually
        // run the SQL against the PDO connection. Then we can calculate the time it
        // took to execute and log the query SQL, bindings and time in our memory.
        try {
            return $callback($query, $bindings);
        }
 
        // If an exception occurs when attempting to run a query, we'll format the error
        // message to include the bindings with SQL, which will make this exception a
        // lot more helpful to the developer instead of just the database's errors.
        catch (Exception $e) {
            throw new QueryException(
                $query, $this->prepareBindings($bindings), $e
            );
        }
    }

**Comment by DejfCold** [comment]
That's correct for postgres. The installation [docker](https://github.com/DejfCold/crater/blob/c7d3b947d9bde7f8b1aef7f06e7f588ee2dc459f/Dockerfile#L27) doesn't support postgres by default, only mysql (which should include mariadb).

A workaround for that would be running the following before attempting the web install process:
```sh
docker exec -ti -u root [container ID] /bin/sh
apt update -y && apt install -y libpq-dev
docker-php-ext-install pdo_pgsql
```

Not sure what's the issue for the MariaDB/Mysql since you haven't posted any error message for that one.

**Comment by RevRebel** [comment]
Thanks that seemed to work although I get the other issue which I believe someone already opened that the database has to be empty. But if it's empty the application throws errors during the initial setup, I  had to use the  "php artisan migrate" first on the database then I was able to bypass the "database has to be empty"  by blocking out lines 81-88 in the EnvironmentManager.php. Now I can get past the URL verification, I'm using Traefik and have enable the headers to pass everything but no matter what I try it can't authentic the session.

**Comment by RevRebel** [comment]
"Not sure what's the issue for the MariaDB/Mysql since you haven't posted any error message for that one"

It's just says "No Driver Found" that's it, but no error message to post. You simply can't move past that step.
