### ISSUE TITLE
Logo not visible on Customer Portal

### ISSUE THREAD

**Issue by b4allb4u** [crater-invoice/crater#714]
Dear Team Members! 

Greetings of the day! 

First of all, Thanks to the entire team for your contribution and hard on making such a beautiful application. I would like to inform you that, Today, I have purchased a white label module and faced the issue of the logo not being visible on the customer portal, Pls resolve. 

**@mohitpanjwani Ji,** Pls, Provide an option to set a custom footer, which will be visible on the customer portal. it will help to add our HTML links, which will be representing our services to customers like **Website, HelpDesk, Community Forum, and Contact us.**

![image](https://user-images.githubusercontent.com/24243794/149149812-dfdd8670-b828-4845-8fe6-ead0e87c6d34.png)

Regards

B4ALLB4U

**Comment by mohitpanjwani** [comment]
Hey @b4allb4u, 

Thanks a lot for your kind words and support. 

The customer portal logo issue has been fixed. Please update your crater app to 6.0.1 to get the new changes. 

Also we'll look into implementing your suggestions for white-labeling soon to allow a better experience for your customers. 

We're already working on adding ability to update the logo for admin portal's dashboard and login page :)

If there's anything else, please feel free to reach out at support@craterapp.com.

**Comment by b4allb4u** [comment]
@mohitpanjwani Ji, Thanks a lot for your new **version 6.0.1**. Now everything is working fine. let me know one thing, How can I edit the main lading information. 
![image](https://user-images.githubusercontent.com/24243794/149328218-0fa2ff15-c30f-46f4-99da-7b3e62f2aad1.png)

**Comment by mohitpanjwani** [comment]
> @mohitpanjwani Ji, Thanks a lot for your new **version 6.0.1**. Now everything is working fine. let me know one thing, How can I edit the main lading information. ![image](https://user-images.githubusercontent.com/24243794/149328218-0fa2ff15-c30f-46f4-99da-7b3e62f2aad1.png)

Glad to hear that. 

Btw we're working on allowing you to update admin logo and the text on the login page.
