### ISSUE TITLE
Estimates showing in main dashboard even if role doesn't allow viewing estimates

### ISSUE THREAD

**Issue by sebmatton** [crater-invoice/crater#722]
**Describe the bug**
Users using a role where the are not allowed to view or manage estimates can still view them in the main dashboard.

**Expected behavior**
Estimates tab shouldn't be displayed on main dashboard

**Screenshots**
![image](https://user-images.githubusercontent.com/4431263/149475496-139a62dc-887e-4acc-9e01-ba87f91e6cb4.png)

**Please complete the following information:**
- Crater version: 6.0.2

**Comment by mohitpanjwani** [comment]
Fixed on https://github.com/crater-invoice/crater/releases/tag/6.0.3
