### ISSUE TITLE
Invoice/Estimate Template Table

### ISSUE THREAD

**Issue by huseyinkogo** [crater-invoice/crater#724]
Wondering how could remove first field on the table for Invoice/Estimate?
Is there are way change "estimate" text  to sales order on the estimate template?

Many thanks

**Comment by Netzlichter** [comment]
You can edit the whole template: https://docs.craterapp.com/guide/custom-templates.html

**Comment by mohitpanjwani** [comment]
Hey, as @Netzlichter suggested, custom template is the only way to do this.
