### ISSUE TITLE
Add Croatian language

### ISSUE THREAD

**Issue by gokkstudio** [crater-invoice/crater#725]
Senpai please add Croatian language, translation attached.
Language: Croatian
Local Name: hrvatski
Language Code: hr
[hr.zip](https://github.com/crater-invoice/crater/files/7871849/hr.zip)

thanks

**Comment by mohitpanjwani** [comment]
Hey, the Croatian language is already added in the latest update. 

Please check it and let me know if you still can't find it :)

**Comment by gokkstudio** [comment]
There are some fields untranslated thatare not in the .json file, some notifications also, can you point me in the right direction what else to translate please?
