### ISSUE TITLE
Moved to a new server

### ISSUE THREAD

**Issue by afyfe** [crater-invoice/crater#731]
Hi,

I've had to move the app to a new server

How do I restore from a backup I took ?

I'd appreciate the help.

Adam

**Comment by mohitpanjwani** [comment]
Hey, Crater exports the database backup on a mysql dump file. 

You can read more about how to use mysqldump to restore an existing backup: https://stackoverflow.com/questions/105776/how-do-i-restore-a-dump-file-from-mysqldump

**Comment by mohitpanjwani** [comment]
Closing this but feel free to reopen if you're still stuck.
