### ISSUE TITLE
Invoice Link as placeholder not working

### ISSUE THREAD

**Issue by Pazekal90** [crater-invoice/crater#735]
**Describe the bug**
The invoice link placeholder that can manually inserted into in the invoice templates is not working. 
At the bottom of an invoice the automatically inserted button has a different link than the placeholder i manually added. 
They should be identical and should work. 

**Expected behavior**

**Screenshots**
<img width="663" alt="Bildschirmfoto 2022-01-17 um 21 24 27" src="https://user-images.githubusercontent.com/25208775/149833672-b8216b24-b4a1-4574-a3b0-3ab8e43ea275.png">

<img width="445" alt="image" src="https://user-images.githubusercontent.com/25208775/149833726-1105c55c-237d-4a0b-b6da-c335d7964a27.png">

<img width="1537" alt="image" src="https://user-images.githubusercontent.com/25208775/149833778-4b14a208-c6cf-407c-aedc-44c4e02e0ccb.png">

**Please complete the following information:**
- Crater version: 6.0.2
- PHP version: 8

**Comment by mohitpanjwani** [comment]
We're thinking of removing the custom link fields in the next update as PDFs can no longer be accessed publicly for security reasons. 

The links sent via emails are stored on email logs and they expire after given days automatically (this setting can be updated). 

Do you use this feature often? What if we ask the customer to login before they can see the PDFs?

**Comment by Pazekal90** [comment]
Then it would be good so set the position of the invoice link by my own. Because it is not always the best place at the bottom of the mail. that's the reason I preferred the custom link in my messages till now.

**Comment by mohitpanjwani** [comment]
We've removed these links on https://github.com/crater-invoice/crater/releases/tag/6.0.3 to avoid these errors. 

@Pazekal90 We'll be using a different email layout from 6.1.0 onwards. Perhaps we can think about a different solution once that's released.
