### ISSUE TITLE
Company logo removal

### ISSUE THREAD

**Issue by szv** [crater-invoice/crater#739]
**Describe the bug**
I uploaded a company logo, which works as expected.
I clicked on the X to remove the logo and saved the company infos.
The company logo is not removed.

**Expected behavior**
The logo can be removed.

**Please complete the following information:**
- Crater version: 6.0.2
- PHP version: 8.0
- Database type and version: MySQL / unknown version

**Optional info**
- User-OS: Windows 11
- Browser: Firefox 96.0.1

**Comment by adil-appifytech** [comment]
@szv - Same issue exist for `Account Settings` image too.

**Comment by mohitpanjwani** [comment]
Issue fixed on https://github.com/crater-invoice/crater/releases/tag/6.0.3
