### ISSUE TITLE
Previous category/customer not automatically selected when editing expense

### ISSUE THREAD

**Issue by sebmatton** [crater-invoice/crater#741]
**Describe the bug**
When editing an expense, the already defined category or customer aren't selected automatically when not in the first 5 items of the select box.

_Suggestion of explanation: It seems that the select box only lists the first 5 possible items. If the previous value is the 6th item, then the select box can't find it by default and loads the default value (choose a value...)_

**Expected behavior**
If a previous value exist, it must be selected by default to avoid loosing information.

**Screenshots**
![image](https://user-images.githubusercontent.com/4431263/150119372-6dd9c999-5ec5-4aa7-aa61-5ddda9e99fdc.png)
![image](https://user-images.githubusercontent.com/4431263/150122031-50849f5d-db8c-41c8-8080-bf381bd684bc.png)

**Please complete the following information:**
- Crater version: 6.0.2
- PHP version: 7.4.21
- Database type and version: MariaDB 10.5.9

**Optional info**
- OS:  Win 10
- Browser: Chrome & Firefox

**Comment by mohitpanjwani** [comment]
This is no longer an issue in the new release. 

Closing it but please feel free to reopen if you still encounter this issue.
