### ISSUE TITLE
Erro login

### ISSUE THREAD

**Issue by michelmelo** [crater-invoice/crater#745]
**Describe the bug**
good morning,
I'm trying to run the project locally and follow all the steps
I'm using docker and locally I get the attached error.

**Please complete the following information:**
- Crater version: 6.0.0
- PHP version: 7.4
- Database type and version: mysql

**Optional info**
- OS:  [e.g. Ubuntu]
- Browser: [e.g. chrome, safari]
![image](https://user-images.githubusercontent.com/159223/150305359-e68090fa-3be9-404f-9448-1076cde7c63b.png)
![image](https://user-images.githubusercontent.com/159223/150305510-d88a66e4-0764-42ed-b64c-1e8899a2ec81.png)

**Comment by mohitpanjwani** [comment]
Hey! What’s does your URL look like? The domain authentication seems to be failing.

**Comment by michelmelo** [comment]
localhost:8080

**Comment by michelmelo** [comment]
https://www.loom.com/share/df0068fa4d05497db543d3524805881e

**Comment by mohitpanjwani** [comment]
> https://www.loom.com/share/df0068fa4d05497db543d3524805881e

If you changed the URL (as appears in the video): 

You need to also edit your .env file: 
```
SANCTUM_STATEFUL_DOMAINS=localhost:8080
SESSION_DOMAIN=localhost
```

The session domain should not contain the port btw.. you can review the rules here: https://docs.craterapp.com/upgrade-guide.html#step-4-add-required-environment-variables

Closing this but please feel free to reopen if you still get this issue.
