### ISSUE TITLE
VAT & VAT ID fileds

### ISSUE THREAD

**Issue by gokkstudio** [crater-invoice/crater#746]
I don't know how to: add fields and display client company data fields on invoice. It's kinda important to have fileds when creating invoice/quote to other companies, fileds like:
VAT:
VAT ID:

Solution would be to have fileds like VAT & VAT ID available by default right below company name, but also not make them mandatory...

I did create a custom filed called "VAT" but it's clunky (only available on client creation page, not on quick edit) and it's not showing up on my invoice/quote...

Any thoughts?

**Comment by gokkstudio** [comment]
anything?

**Comment by mohitpanjwani** [comment]
> anything?

You can add the VAT ID directly in the default formats on Settings - customisation page.

**Comment by gokkstudio** [comment]
How?, there is no VAT filed in "Settings > Customization > Default Formats > Insert Fields", also no custom fields that I created are shown there..

I have created custom field "VAT" for both estimate and clients, but it has no purpose when populated (when adding new client) because it doesn't show in generated PDF estimate file..

What I ask is: can VAT or/and VAT ID fileds simply be regular non-mandatory fileds when adding new client and also shown on invoices/estimates?

**Comment by gokkstudio** [comment]
Any word on this please?

**Comment by amendogni** [comment]
I support this request too. It is a common field that I would like to report in invoice with the customer information. 
I created the custom field to keep the information in customers database but I couldn't manage to display the VAT in the invoice in the customer field ("Invoice to")

**Comment by mohitpanjwani** [comment]
@gokkstudio @amendogni Whose VAT ID do you wish to display on the Invoice (Customer or your Company's)? 

If you need to display a custom field inside Customer's Billing or Shipping address then you can easily add that on Customization -> Billing Address Format: 
<img width="1685" alt="CleanShot 2022-01-27 at 13 46 29@2x" src="https://user-images.githubusercontent.com/8002555/151318974-e83ddb14-aa63-4185-8ea8-074838c05f9e.png">

If you need to display a static VAT ID for your company which stays the same in all Invoices, then just write it down on the Format like this: 

<img width="459" alt="CleanShot 2022-01-27 at 13 48 13@2x" src="https://user-images.githubusercontent.com/8002555/151319206-8ecdcfc1-b444-4199-960a-980592f53644.png">

**Comment by gokkstudio** [comment]
I need to display both customer's VAT on invoices/quotes and my company VAT, it doesn't work as you suggested. I've tested in your online demo: created a custom field VAT (customer), added it Customer's Billing and it's not showing up on invoice/qoute. Then I created another field: VAT 2 (estimate) and added it Customer's Billing, its also not showing up on invoices/quotes...

Only if I insert custom field (VAT) in estimate "Notes" then it shows up...

Can you please update those fileds to be defaults but not mandatory in next release. 
Also it would be handy if we could enable/disable fields in "Customization" when adding new clients. In my example I only need:
• client company (or personal name)
• email address (but not mandatory)
• address 
• VAT
..and don't even need any other fields.
![Screenshot (15)](https://user-images.githubusercontent.com/19394068/151393814-7571523b-c9fc-47b0-84f5-ef0cf1d6ae86.png)

**Comment by amendogni** [comment]
Thanks, the first solution worked for me

**Comment by gokkstudio** [comment]
Thank you
