### ISSUE TITLE
Whitelabel

### ISSUE THREAD

**Issue by gokkstudio** [crater-invoice/crater#747]
Are we able to customize the login screen and remove Crater links by purchasing Whitelabel for selfhosted version on a single domain/subdomain?

Just need a confirmation so I could make a purchase

**Comment by mohitpanjwani** [comment]
Hey, 

In the current version of white-label module, you can update the color theme + logo for customer portal and color theme for admin portal. 

We're working on adding the ability to update logo for admin portal, admin login page and change the text on login page too. New update should be available soon 👍

**Comment by gokkstudio** [comment]
Feel free to message me when you have it done, I'm gonna be buying it. Thanks

**Comment by mohitpanjwani** [comment]
Thanks! I'll DM You. 

Closing this for now :)

**Comment by tony-carlos** [comment]
I have purchased  white label  but when I try to install it says Module Not Available I need help plz
