### ISSUE TITLE
Can't see PDF in the invoice view

### ISSUE THREAD

**Issue by mihha** [crater-invoice/crater#749]
**Describe the bug**
PDF preview doesn't show PDF file. Just offers to download it

**Expected behavior**
Show PDF file

**Screenshots**
![image](https://user-images.githubusercontent.com/3791124/150628992-9e08ede9-7b28-4929-8c54-22700e4f6483.png)

**Please complete the following information:**
- Crater version: 6.0.2
- PHP version: 7.4.27
- Database type and version: MySQL  8.0.27-0ubuntu0.20.04.1

**Optional info**
- OS: Ubuntu
- Browser: Chrome

**Comment by mihha** [comment]
Anyone please?

**Comment by mohitpanjwani** [comment]
I've never seen this one 🤔 I think it might be something to do with Browser or OS itself. Can you try on a different browser?

**Comment by mihha** [comment]
Turns out this is a Brave browser "feature"

You can configure it to either show PDF in internal viewer or just offer to download it

I apologize for false alert 🙁

**Comment by mohitpanjwani** [comment]
No worries! Thanks for letting us know about the feature 👍
