### ISSUE TITLE
Request for Unicode support

### ISSUE THREAD

**Issue by khalequzzaman17** [crater-invoice/crater#751]
The application doesn't support Unicode at PDF (invoice). I tried to translate the project in Bangla (Bengali), but the PDF broke the template. Could you please add the feature to the application so that the project works properly?

**Comment by mohitpanjwani** [comment]
> The application doesn't support Unicode at PDF (invoice). I tried to translate the project in Bangla (Bengali), but the PDF broke the template. Could you please add the feature to the application so that the project works properly?

Hey, it Crater PDFs do supports unicode in the current version (which characters break the PDF exactly for you?)
