### ISSUE TITLE
Invoice creation with Android app partially incomplete

### ISSUE THREAD

**Issue by sebmatton** [crater-invoice/crater#765]
**Describe the bug**
When creating an invoice using android application, some fields in the database are not filled correctly. The total amount of those invoices becomes 0.0€ in reports and dashboards, the invoices are not taken into account.

> **_Possible investigation:_**
>
> Having a look in the database shows that at least the following fields are empty in the DB record for `invoice`:
> `exchange_rate`, `base_discount_val`, `base_sub_total`, `base_total`, `base_tax`, `base_due_amount`
>
> and the following fields are empty in the DB record for `invoice_items`:
> `unit_name`, `item_id`, `base_price`, `exchange_rate`, `base_discount_val`, `base_tax`, `base_total`
>
> I suspect there is some troubles using the predefined item, but it may be some other root cause.

**Expected behavior**
No loss of information, reliable information in dashboard and report.

**Please complete the following information:**
- Crater version: 6.0.2
- PHP version: 7.4.21
- Database type and version: MariaDB 10.5.9

**Optional info**
- OS:  Android
- Browser: Crater application

**Comment by mohitpanjwani** [comment]
We've deployed a new update on mobile app to fix this. The currency_id wasn't getting passed which is why it didn't save the needed fields correctly. 

https://github.com/crater-invoice/crater-mobile/commit/f9955f711afe15b0d6291331d988e2d26937d7f2
