### ISSUE TITLE
unable to connect database

### ISSUE THREAD

**Issue by bobforgiarini** [crater-invoice/crater#769]
Hello,
when i tried to connect my database it wrote everything in the database, but gave the following error message.
![image](https://user-images.githubusercontent.com/42447647/152242904-9a1a43d2-a072-464c-b235-e3a768b79382.png)
Crater Version: 6.0.2 & 6.0.1
PHP Version: 7.4.8
DB Type & Version: 10.3.23-MariaDB

**Comment by mohitpanjwani** [comment]
Hey @bobforgiarini, this is the first time I see an error like this. 

Where exactly are you trying to install Crater, can you mention the Operating System?

Is it on shared hosting where they've disabled debug_backtrace()?

**Comment by bobforgiarini** [comment]
Hey,
correctly i tried to install it on a shared hosting, i will ask them if they've disabled it.
I will try later to install it on a simple vserver.

**Comment by mohitpanjwani** [comment]
Cool @bobforgiarini, Closing this issue as it's not an issue with Crater but feel free to reopen if you still cannot continue with the installer on a different server.
