### ISSUE TITLE
Install On Synology 

### ISSUE THREAD

**Issue by netspear** [crater-invoice/crater#776]
Anyone know how I can install as a docker on Synology?

**Comment by dominikspeh** [comment]
On my synology DS220+ I have a running crater installation with docker:

- Install docker via synology software center
- Enable ssh (settings -> terminal & snmp)
- Download latest crater version from github, move and zip it on NAS
- Set file/folder permissions
- Connect to NAS via ssh (ssh username@NAS-IP) and navigate to crater folder
- Continue with step 4 from crater documentation (https://docs.craterapp.com/installation.html#docker-installation)

Maybe you need to change the ngix port in docker-compose.yml

Hope you get it running ;)
