### ISSUE TITLE
Update expense not working

### ISSUE THREAD

**Issue by maxpdesign** [crater-invoice/crater#777]
**Describe the bug**
When I try to update an already existing expense, it doesn't work. Update expense button keeps loading.
After page refresh, changes aren't visible so they are not saved.

**Expected behavior**
The changes to the expense are saved and I am redirected to the expenses overview page

**Screenshots**
![Screenshot 2022-02-07 at 15 02 33](https://user-images.githubusercontent.com/32506878/152804362-79c0f617-5224-4884-b166-af52d37a73e1.png)

![Screenshot 2022-02-07 at 15 02 56](https://user-images.githubusercontent.com/32506878/152804384-de1480f7-e359-4897-b2bb-a86ab7fa25e9.png)

**Please complete the following information:**
- Crater version: 6.0.2
- PHP version: 7.4
- Database type and version: mysql  Ver 14.14 Distrib 5.7.35-38, for debian-linux-gnu (x86_64) using  7.0

**Optional info**
- OS:  Linux (server)
- Browser: Chrome

**Comment by mohitpanjwani** [comment]
Fixed on https://github.com/crater-invoice/crater/releases/tag/6.0.3
