### ISSUE TITLE
Cross-Site Request Forgery (CSRF) in bytefury/crater

### ISSUE THREAD

**Issue by HDVinnie** [crater-invoice/crater#779]
Per security.md we have sent out multiple email back in November and December with no response. Please follow up. 

https://huntr.dev/bounties/835fa2a7-fe43-4f9b-a9a5-543496bf2351/

**Comment by mohitpanjwani** [comment]
We missed those as they were on the old repository but thanks for the reminder. 

We have replied/updated the status.
