### ISSUE TITLE
Custom Select Field gets cut off after first 3 options.

### ISSUE THREAD

**Issue by klementj** [crater-invoice/crater#780]
When looking into issue #676 I found a problem with the fixed height of the page and the dropdown. See original reply below:

Thank you for finding a bug and coming up with a solution ( PR #678 ) . While doing a review I started debugging the problem. It looks like the problem is not with the dropdown, but with the invoice page having a fixed height of 100vh and then the section with items, notes and custom fields having overflow:hidden. This cuts of of the rest of the ul with the options off, and never showing a scrollbar. 

![Here is the overflow hidden](https://user-images.githubusercontent.com/222317/152867692-7e952408-27cc-440d-a867-5e4b0d36846d.png)

Even if the page height is set to min-height: 100vh a scrollbar would appear on the page when the dropdown is opened. This is an old problem with custom dropdowns. They need to detect when they are at bottom of page and show options above. Dropdown should poperly be rewritten with JS to detect or use the [HTML select element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select). I'll open an issue for this later, for now I think we should just go with the quick fix that you provided. What does @mohitpanjwani think?

_Originally posted by @klementj in https://github.com/crater-invoice/crater/issues/676#issuecomment-1031903390_

**Comment by mohitpanjwani** [comment]
Fixed on https://github.com/crater-invoice/crater/releases/tag/6.0.3
