### ISSUE TITLE
Wrong cookie domain

### ISSUE THREAD

**Issue by Wunderharke** [crater-invoice/crater#783]
**Describe the bug**
I currently can not comlete step 4 of the installation.
The session cookie verification fails.

**Expected behavior**
The verification should pass as the domain is set correctly.

**Futher Information**
I looked into the cookies and it seems the domain defined there is the correct one but with a addition dot in front (also vaild for further subdomains).
~~It doesn't seem correct and the wizard does not allow leading dots either.~~

Firefox console tells me "Cookie "XXX" has been rejected because it is already expired. Chrome doesn't say anything about this,

**Comment by davwheat** [comment]
I had this issue too.

I worked around it by completing setup in Incognito mode in Chrome (I imagine Firefox Private Browsing would work too), and this fixed the issue.

**Comment by mohitpanjwani** [comment]
Please try the fix mentioned by @davwheat. 

It should work 👍

Feel free to reopen if the issue still persists.
