### ISSUE TITLE
Could not find driver installation error

### ISSUE THREAD

**Issue by cryogenic** [crater-invoice/crater#787]
Trying to install on shared hosting. this error display why im trying to use mysql. if im using sqlite, error display Database should be empty. Try to delete the database in Database folder, error display Database does not exist.

**Screenshots**
![2022-02-11 12_25_23-Window](https://user-images.githubusercontent.com/351299/153538689-1de37fff-acab-44fb-8a5d-022112353c56.png)

![2022-02-11 12_48_59-Crater - Self Hosted Invoicing Platform](https://user-images.githubusercontent.com/351299/153539970-fc2950d2-e709-40fb-8cbd-1cd4ae8e20db.png)

**Please complete the following information:**
- Crater version: 6.0.2
- PHP version: 8.0
- Database type and version: 10.1.48-MariaDB - MariaDB Server

**Optional info**
- OS:  Linux - Litespeed
- Browser: Chrome

**Comment by wyattmcgehee** [comment]
If you aren't running with Docker, from a cli, do `php -m`, and see which modules are loaded.

Look for mysqlnd and pdo_mysql, and if they aren't listed, get them installed for your system.

You can do a `php -i | grep mysql` instead if you want to grep a full info dump.

**Comment by cryogenic** [comment]
well... problem solved.. i think...

1. i lower the php version to 7.4 which is Crater requirement.
2. use sqlite. when erorr "database should be empty"
 display, pragma some things to drop all table, vacuum, and integrity check. but stuck again on next step. CSRF token error.
3. restart whole process all over again, install using incognito windows, all done!
