### ISSUE TITLE
Downloading Receipt gets to 404 Not Found

### ISSUE THREAD

**Issue by cgg507** [crater-invoice/crater#788]
**Describe the bug**
When trying to download an uploaded expense receipt, you would get a 404 - Not Found Error.

I tried this in my own deployment of crater and in your demo site.

**Expected behavior**
Receipt should be accesible when clicking the "Download Receipt" Button in the Edit Expense view.

**Screenshots**
![imagen](https://user-images.githubusercontent.com/17771096/153697668-4821ca66-b42e-4d8c-ac5e-bd405ae3143b.png)
![imagen](https://user-images.githubusercontent.com/17771096/153697677-092a0a44-460f-4033-9d18-87d280f6a2d9.png)

**Please complete the following information:**
- Crater version: 6.0.2
- PHP version: 7.4
- Database type and version: MariaDB 10.6.5

**Optional info**
- OS:  Ubuntu 20.04 as Docker host.
- Browser: Tried on Firefox, Edge.

**Comment by mohitpanjwani** [comment]
Fixed on https://github.com/crater-invoice/crater/releases/tag/6.0.3
