### ISSUE TITLE
Not able to update to latest version

### ISSUE THREAD

**Issue by Xoshbin** [crater-invoice/crater#798]
I can't update the app from the dashboard settings

**Please complete the following information:**
- Crater version: 6.0.2
- PHP version: 8.0
- Database type and version: MySql

**Optional info**
- OS:  Ubuntu
- Browser: chrome

**Stack**
production.ERROR: Call to undefined function Crater\Http\Controllers\V1\Admin\Update\set_time_limit() {"userId":1,"exception":"[object] (Error(code: 0): Call to undefined function Crater\\Http\\Controllers\\V1\\Admin\\Update\\set_time_limit() at /home/runcloud/webapps/accounting/app/Http/Controllers/V1/Admin/Update/CheckVersionController.php:27)

**Comment by mohitpanjwani** [comment]
Hey, Hey, It looks like this function is disabled on your host for some reason. 

You can comment that out or remove the given line to update.
