### ISSUE TITLE
Invoice date and due date change on invoice edit.

### ISSUE THREAD

**Issue by ndziuba** [crater-invoice/crater#799]
**Describe the bug**
When i created an invoice and i want to edit it before sending it out, 
it offen (but not always) happens that the invoice and due date are set back by one day.
For example:
05.02 gets set back to 04.02
and the due date 12.02 gets set back to 11.02.

So right now i have to double check if the dates are correct before sending an invoice that got edited.
If i go back and edit the dates manually again, back to 05.02 and 12.02, it gets saved as expected.

**Please complete the following information:**
- Crater version: 6.0.2
- Docker Compose install

**Comment by mohitpanjwani** [comment]
Fixed on https://github.com/crater-invoice/crater/releases/tag/6.0.5
