### ISSUE TITLE
Docker installation fails

### ISSUE THREAD

**Issue by koopernick** [crater-invoice/crater#805]
**Describe the bug**
The docker installation fails following your guide => https://docs.craterapp.com/installation.html#docker-installation

```
root@Portainer:/var/www/crater# ./docker-compose/setup.sh
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Package operations: 175 installs, 0 updates, 0 removals


  [RuntimeException]
  /var/www/vendor does not exist and could not be created.


install [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--dry-run] [--dev] [--no-suggest] [--no-dev] [--no-autoloader] [--no-progress] [--no-install] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--] [<packages>]...


Warning: require(/var/www/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/artisan on line 18

Fatal error: require(): Failed opening required '/var/www/vendor/autoload.php' (include_path='.:/usr/local/lib/php') in /var/www/artisan on line 18

Warning: require(/var/www/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/artisan on line 18

Fatal error: require(): Failed opening required '/var/www/vendor/autoload.php' (include_path='.:/usr/local/lib/php') in /var/www/artisan on line 18
```

**Expected behavior**
The installation should work.

**Please complete the following information:**
- Crater version: 6.0.4

Edit : the manual installation fails too => https://docs.craterapp.com/installation.html#manual-installation
I get a 500 error from nginx

`192.168.1.42 - - [21/Feb/2022:10:09:01 +0000] "GET / HTTP/1.1" 500 5 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36 Edg/98.0.1108.55" "-"`

What's the best way to install your product ?

**Comment by koopernick** [comment]
Since I didn't get any reply here, I went with akaunting, which is exactly the same but with a working installation.

**Comment by 3isenHeiM** [comment]
_For posterity_
After running the `docker-compose up -d` command, execute this inside the `crater` directory :

```
 sudo chown -R 1000:1000 .   
```

And the `./docker-compose/setup.sh` will run without any problems!

**Comment by imlegend19** [comment]
For windows users:

```bash
cd /path/to/crater/directory
takeown /R /F .
icacls . /grant administrators:F /T
```

And start the docker container:

```bash
docker-compose up -d
./docker-compose/setup.sh
```
