### ISSUE TITLE
Unable to update invoice ID format

### ISSUE THREAD

**Issue by mzagmajster** [crater-invoice/crater#825]
**Describe the bug**
Installed Crater for the first time. Tried to change invoice ID format (INV-0001) by adding new components to format (year), when tried to save the change I got an error about currency not being in array.

After investigating a bit it looks like the problem lies in the file: cat Http/Controllers/V1/Admin/Settings/UpdateCompanySet
tingsController.php
```

    public function __invoke(UpdateSettingsRequest $request)
    {
        $company = Company::find($request->header('company'));
        $this->authorize('manage company', $company);

        $companyCurrency = CompanySetting::getSetting('currency', $request->header('company'));
        $data = $request->settings;

        if ($companyCurrency !== $data['currency'] && $company->hasTransactions()) {
            return response()->json([
                'success' => false,
                'message' => 'Cannot update company currency after transactions are created.'
            ]);
        }

        CompanySetting::setSettings($data, $request->header('company'));

        return response()->json([
            'success' => true,
        ]);
    }

```

$data does not contain the currency key in the array. I commented out the if statement and I was able to save the settings.

**Expected behavior**
Expect to be able to save settings successfully.

**Screenshots**

**Please complete the following information:**
- Crater version: 6.0.5
- PHP version: 8.1
- Database type and version: MariaDB 10

**Comment by mohitpanjwani** [comment]
Issue has been fixed: https://github.com/crater-invoice/crater/pull/821

We will create an automatic update for this in a few hours but if you need to fix it right away, you can update the file manually as given in the pull request.

**Comment by mohitpanjwani** [comment]
Update released: https://github.com/crater-invoice/crater/releases/tag/6.0.6

You can update your app automatically from Settings -> Update App page.
