### ISSUE TITLE
Unable to complete installation steps in localhost using xampp

### ISSUE THREAD

**Issue by mdmusaib** [crater-invoice/crater#839]
Hi team, 
Hope you are doing great, 
Actually my concern is I'm installing crater app in localhost, I have cloned the latest git repository, 
And changed the env based on my localhost xamppp configuration, 
But in database installation step I'm getting multiple error, please try to help ne to fix this issue.. 

Below I'm attaching the screenshot and changed env file

![IMG_20220309_072239](https://user-images.githubusercontent.com/19144712/157357238-ee04f112-d594-4895-85ba-0fbd603000b5.jpg)
![IMG_20220309_072242](https://user-images.githubusercontent.com/19144712/157357279-48d350fb-d2f3-4278-b764-5eb8d9b1f956.jpg)
![IMG_20220309_072708](https://user-images.githubusercontent.com/19144712/157357343-c59fa99c-4b9a-41b8-8481-726aee635ba4.jpg)

**Comment by mdmusaib** [comment]
Hi team, 
Can anyone suggest how to quickly we can resolve

**Comment by mohitpanjwani** [comment]
> Hi team, Hope you are doing great, Actually my concern is I'm installing crater app in localhost, I have cloned the latest git repository, And changed the env based on my localhost xamppp configuration, But in database installation step I'm getting multiple error, please try to help ne to fix this issue..
> 
> Below I'm attaching the screenshot and changed env file
> 
> ![IMG_20220309_072239](https://user-images.githubusercontent.com/19144712/157357238-ee04f112-d594-4895-85ba-0fbd603000b5.jpg) ![IMG_20220309_072242](https://user-images.githubusercontent.com/19144712/157357279-48d350fb-d2f3-4278-b764-5eb8d9b1f956.jpg) ![IMG_20220309_072708](https://user-images.githubusercontent.com/19144712/157357343-c59fa99c-4b9a-41b8-8481-726aee635ba4.jpg)

Hey buddy, I think it would be better if you use something like Laragon with Nginx instead of xamp. Also I hope you're not running this with php artisan serve because that doesn't work on Crater.

**Comment by mdmusaib** [comment]
Okay thanks for the info, I was using php artisan serve command. Hope that will  not work, 
I will check how to run laragon with nginx
