### ISSUE TITLE
Cannot update expense

### ISSUE THREAD

**Issue by calumshep** [crater-invoice/crater#854]
**Describe the bug**
When pressing the update expense button to save the changes made to the form (adding a note to an existing expense), the spinner just constantly spins and nothing happens.

**Expected behavior**
The expense would be updated and the page would move on.

**Screenshots**
<img width="508" alt="image" src="https://user-images.githubusercontent.com/29754812/159263054-52eb9b94-add1-4ae1-b17f-ec8fdbef008c.png">

**Comment by mohitpanjwani** [comment]
I cannot reproduce this issue on my side. 

Can you specify more details like your crater version, PHP version, OS, and Server on which you're running Crater? Also please specify if you're using docker or manual installation.

**Comment by calumshep** [comment]
Was using an outdated crater version. Is fixed in at least 6.0.6 - apologies!
