### ISSUE TITLE
TAX is not computed correctly when discount applied

### ISSUE THREAD

**Issue by scramatte** [crater-invoice/crater#889]
Hi,

TAX amount is not computed correctly when discount applied.
I've got VAT tax of 21% 

If you made an invoice, add product with TAX  and set discount (fixed or percentage) the amount of TAX is calculated without take in count the discount value.

For example:
The correct amount will be the following:
3 x  45€   - 60€ discount = 75€     , tax amount (21%) =  75*21/100 = 15,75€ , total = 90,75

Crater do the following incorrect computation
3 x  45€   - 60€ discount = 75€     , tax amount (21%) = 135*21/100 = 28,35 , total = 103,75  

It's quite annoying issue.
Please fix it asap

Regards

**Comment by tamsir** [comment]
Hello,
Can you give more information. For example, the file concerned .
Thanks

**Comment by profiteroles1** [comment]
Good lord. I can confirm this is an issue. I invoiced hundreds of clients with the wrong amounts because the sales tax is not being calculated on the discounted amount. PLEASE FIX THIS ASAP

**Comment by profiteroles1** [comment]
Here is a video that shows the issue:

<a href='https://www.youtube.com/watch?v=YUDk66yycGQ'><img width="1214" alt="Screen Shot 2022-06-08 at 1 17 41 PM" src="https://user-images.githubusercontent.com/88507326/172677853-2c3db5a4-61e4-4847-ab9d-8058232dacd6.png"></a>

**Comment by profiteroles1** [comment]
@mohitpanjwani please help us with this!

**Comment by mohitpanjwani** [comment]
Yeah I can confirm that this is an issue when tax per item and discount per item both are enabled. 

We will release a fix urgently.

**Comment by profiteroles1** [comment]
> Yeah I can confirm that this is an issue when tax per item and discount per item both are enabled.
> 
> We will release a fix urgently.

Thank you! Can you also please let us know what code to change so we can apply to our live installation of crater?

**Comment by mohitpanjwani** [comment]
> > Yeah I can confirm that this is an issue when tax per item and discount per item both are enabled.
> > We will release a fix urgently.
> 
> Thank you! Can you also please let us know what code to change so we can apply to our live installation of crater?

https://github.com/crater-invoice/crater/pull/953

The above PR fixes the issue.

**Comment by profiteroles1** [comment]
Thank you very much @mohitpanjwani for fixing this! I was also hoping you might be able to take a look at this issue:
https://github.com/crater-invoice/crater/issues/929

We have never been able to use custom values because they are not correctly loaded from the database after they are set. We have a custom value set on the Customer model, and every time we edit a customer, we must look at the database to see the custom values, copy them, and paste them back into the fields. Your help is very much appreciated :)

**Comment by tamsir** [comment]
Hello, 
I get a problem with rounded tax
I solved it by doing in resources/scripts/admin/stores/invoice.js

    ```
  getTotalTax() {
        if (
          this.newInvoice.tax_per_item === 'NO' ||
          this.newInvoice.tax_per_item === null
        ) {
          return this.getTotalSimpleTax + this.getTotalCompoundTax
        }
        return _.sumBy(this.newInvoice.items, function (tax) {
          return ((Math.round(tax.tax/100))*100) // Ajout problème Total Taxe
        })
      },
```
