### ISSUE TITLE
Add Thai Language to Crowdin

### ISSUE THREAD

**Issue by chestnutbak** [crater-invoice/crater#919]
Please add the Thai Language to Crowdin so we can get our translators working on translating the UI.

Thanks!

**Comment by chestnutbak** [comment]
Pretty please @mohitpanjwani

**Comment by mohitpanjwani** [comment]
@chestnutbak there's already a PR for this https://github.com/crater-invoice/crater/pull/768

I think it would work great for your use case as adds support for changing the language on PDFs too.

**Comment by mohitpanjwani** [comment]
Yes, it covers both.

Anyhow, I've added thai language to crowdin as well. That should fix it. 

Also, I'm merging this PR as it looks ready now.

**Comment by chestnutbak** [comment]
Thanks for working on this! When will this be released via an update? We are itching to be able to use this with Thai.
