### ISSUE TITLE
Can't install on a server

### ISSUE THREAD

**Issue by lMagickl** [crater-invoice/crater#932]
**Describe the bug**
During the installation process I get an error during the DB initialization

Error
EDIT:
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'json null, `boolean_answer` tinyint(1) null, `date_answer` date null, `time_answ' at line 1 (SQL: create table `custom_fields` (`id` bigint unsigned not null auto_increment primary key, `name` varchar(255) not null, `slug` varchar(255) not null, `label` varchar(255) not null, `model_type` varchar(255) not null, `type` varchar(255) not null, `placeholder` varchar(255) null, `options` json null, `boolean_answer` tinyint(1) null, `date_answer` date null, `time_answer` time null, `string_answer` text null, `number_answer` bigint unsigned null, `date_time_answer` datetime null, `is_required` tinyint(1) not null default '0', `order` bigint unsigned not null default '1', `company_id` int unsigned not null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8 collate 'utf8_unicode_ci')

**Expected behavior**
Go to the next step of the installation

**Screenshots**

**Please complete the following information:**
- Crater version: 6
- PHP version: 7.4.25
- Database type and version: MYSQL v.5.6

**Optional info**
- OS:  I don't know but I guess it's a Linux
- Browser: chrome

**Comment by starpunjabi** [comment]
> **Describe the bug** During the installation process I get an error during the DB initialization
> 
> Error EDIT: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'json null, `boolean_answer` tinyint(1) null, `date_answer` date null, `time_answ' at line 1 (SQL: create table `custom_fields` (`id`bigint unsigned not null auto_increment primary key,`name`varchar(255) not null,`slug`varchar(255) not null,`label`varchar(255) not null,`model_type`varchar(255) not null,`type`varchar(255) not null,`placeholder`varchar(255) null,`options`json null,`boolean_answer`tinyint(1) null,`date_answer`date null,`time_answer`time null,`string_answer`text null,`number_answer`bigint unsigned null,`date_time_answer`datetime null,`is_required`tinyint(1) not null default '0',`order`bigint unsigned not null default '1',`company_id`int unsigned not null,`created_at`timestamp null,`updated_at` timestamp null) default character set utf8 collate 'utf8_unicode_ci')
> 
> **Expected behavior** Go to the next step of the installation
> 
> **Screenshots**
> 
> **Please complete the following information:**
> 
>     * Crater version: 6
> 
>     * PHP version: 7.4.25
> 
>     * Database type and version: MYSQL v.5.6
> 
> 
> **Optional info**
> 
>     * OS:  I don't know but I guess it's a Linux
> 
>     * Browser: chrome

Please check this video for installation steps: https://www.youtube.com/watch?v=waheY7LHBdc

**Comment by lMagickl** [comment]
Thank you it worked ! :)
