### ISSUE TITLE
Docker error - php7-bcmath (no such package)

### ISSUE THREAD

**Issue by PsHyC0** [crater-invoice/crater#937]
**Describe the bug**
Following instructions to install in Docker but docker-compose install fails 

**Expected behavior**
Install should work

**Screenshots**
❯ docker-compose up -d
Building cron
Sending build context to Docker daemon  22.06MB
Step 1/5 : FROM php:7.4-fpm-alpine
 ---> 34906ce9abcf
Step 2/5 : RUN apk add --no-cache     php7-bcmath
 ---> Running in dab09129c29f
fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/community/x86_64/APKINDEX.tar.gz
ERROR: unable to select packages:
  php7-bcmath (no such package):
    required by: world[php7-bcmath]
The command '/bin/sh -c apk add --no-cache     php7-bcmath' returned a non-zero code: 1
ERROR: Service 'cron' failed to build : Build failed

**Please complete the following information:**
- Crater version: 6.06
- PHP version: 7?
- Database type and version: 

**Optional info**
- OS:  Ubuntu 20.04
- Browser: n/a

I downloaded the file at https://dl-cdn.alpinelinux.org/alpine/v3.16/community/x86_64/APKINDEX.tar.gz and untarred it and it appears the PHP version in there has upgraded to 8 so there's no php7-bcmath only php8-bcmath.

**Comment by mBilG** [comment]
Had the same issue..

I changed the following from crater > docker-compose > cron.dockerfile : 
Replace " FROM php:7.4-fpm-alpine "
with: " FROM php:8.0-fpm-alpine "

worked fine afterwards..

**Comment by benninkcorien** [comment]
Thanks! The full code in the cron.dockerfile file that seems to work is:

    FROM php:8.0-fpm-alpine
    RUN apk add --no-cache \
        php8-bcmath
    
    RUN docker-php-ext-install pdo pdo_mysql bcmath

    COPY docker-compose/crontab /etc/crontabs/root

    CMD ["crond", "-f"]
