### ISSUE TITLE
Can't install development version to local vm

### ISSUE THREAD

**Issue by df-a** [crater-invoice/crater#938]
**Describe the bug**
I have been trying to install crater developer version to a local vm to be able to customize it correctly, but no matter what I do I can't get a usable website to actually install it. Only 404 errors.

Build completes, but there are some version mismatches with vue colorpicker. Whatever is in the build, can't be served. The VM itself serves php fine, and has the required php extensions as evidenced by the included phpinfo() snippet.

 I only keep getting 404 errors. If I put it a test php file in the public folder, I can navigate to it in the browser, but I can't get crater itself going, I only get 404 errors.

**Expected behavior**
I should be able to get into the install/config screen of crater when I browse to the localhost url where the files are located in order to install and use Crater.

**Screenshots**
![Screen Shot 2022-05-26 at 16 59 20](https://user-images.githubusercontent.com/1872835/170579343-f13b12ee-496e-4b73-889c-a147856a8076.png)
![Screen Shot 2022-05-26 at 16 35 55](https://user-images.githubusercontent.com/1872835/170577921-150355ec-1f92-48f3-83e4-cdc2db0edf16.png)

**Please complete the following information:**
- Crater version: 6.0.6
- PHP version: 7.4.29
- Database type and version: postgres but I never get to the screen to activate this

**Optional info**
- OS:  Debian, specifically Linux 9da21463a9f8 5.10.47-linuxkit

- Browser: brave, ff dev, waterfox

**Comment by mohitpanjwani** [comment]
Looks like an issue with nginx. Are you using a custom configuration?

**Comment by starpunjabi** [comment]
Please check this playlist for Crater Invoice installation videos on localhost and on Cpanel.
https://www.youtube.com/playlist?list=PLNf265MCiIeTTCA5lu90Me2mAkWPm9HWl
