### ISSUE TITLE
can't install asking Error  CSRF token mismatch. 

### ISSUE THREAD

**Issue by bajpangosh** [crater-invoice/crater#951]
**Describe the bug**
can't install stage 4 getting  CSRF token mismatch. 

**Screenshots**
https://snipboard.io/eS0vFf.jpg
**Please complete the following information:**
- Crater version: latest
- PHP version: 7.4
- Database type and version: maria db

**Optional info**
- OS:  [e.g. Ubuntu] Ubuntu
- Browser: [e.g. chrome, safari] chrome

**Comment by bajpangosh** [comment]
now found another issue in Recurring Invoices frequency
**there is no yearly option** 
https://snipboard.io/LWz05J.jpg 
version 6.0.6 but your demo version 6.0.4 have no issue

**Comment by mohitpanjwani** [comment]
Closing this since this is an Nginx issue. 

Also the yearly option has been renamed to `'Every year on the first day of january at 00:00'`
