### ISSUE TITLE
Customer email shouldn't be restricted as unique

### ISSUE THREAD

**Issue by swiderskimarcin** [crater-invoice/crater#952]
There is many companies which are owned by same people and they use same email for contact.

Why not just let customers own same email  ?

**Comment by rihards-simanovics** [comment]
Although technically you are right, I think in this case the assumption is, that, whoever installs this software will act as a host as well as use it themselves, especially as there is no cloud version available. Also, I don't think someone will owe so many companies where updating one email template will become too bothersome.

**Comment by swiderskimarcin** [comment]
> _Although technically you are right, I think in this case the assumption is, that, whoever installs this software will act as a host as well as use it themselves, especially as there is no cloud version available. Also, I don't think someone will owe so many companies where updating one email template will become too bothersome._

I think it's  a misunderstanding :), correct me if i'm wrong ...
I'm not talking about users and many app instalations ... 

I have installed crater app on my server, i have a list of customers witch i want to create and send invoices by provided customer email address. Now every customer needs to have a unique email address but often fiev companies has same owner and ability to provide same email address would be nice (for sending invoices)

**Comment by mohitpanjwani** [comment]
Email must be unique for each customer in a company to allow customers to login to customer portal. How else would customer portal login work? Two customers cannot use the same email similar to how two people cannot create two accounts anywhere with same email address. 

You can use a temporary email for now if this is a blocker for you. Just change the address when sending the invoice.
