### ISSUE TITLE
Blank Page on Installation 

### ISSUE THREAD

**Issue by notPradip** [crater-invoice/crater#961]
did everything mentioned in the installation guide but I am getting blank page while trying to visit the site.
**PS: I am running this app on Digital Ocean's Droplet.**
What Can Be the reason for this?
![Capture](https://user-images.githubusercontent.com/18046492/174156993-7481c607-0c22-428a-82eb-87a0956c6576.PNG)

**Comment by santaaaron** [comment]
I had this problem and it was related to a Cloudflare setting. Sorry, I forgot which setting it was but I think it was in the SSL/TLS section. Hope that helps.
