### ISSUE TITLE
Company logo & User Profile picture uploaded in Settings is not getting displayed to the user

### ISSUE THREAD

**Issue by gokultw** [crater-invoice/crater#991]
**Describe the bug**
Company logo uploaded in Company Information section is not getting displayed to the user

**Steps to reproduce:**

1. login to crater
2. Navigate to settings → Company Information
3. Upload a logo and save

**Expected:** Uploaded logo should be displayed
**Actual:** Logo is not displayed
**Screenshots**
<img width="1104" alt="image" src="https://user-images.githubusercontent.com/104197616/179693733-8878e647-5298-4e47-a5fe-6ad8ddd6884a.png">

User Profile Picture uploaded in Account Settings section is not getting displayed to the user

**Steps to reproduce:**

1. login to crater
2. Navigate to settings → Account Settings
3. Upload a Profile Picture and save

**Expected:** Uploaded Profile Picture should be displayed
**Actual:** Profile Picture is not displayed
**Screenshots**
<img width="1203" alt="image" src="https://user-images.githubusercontent.com/104197616/179693638-9c0ea72e-eec3-40d6-bd28-e9529b6a57fd.png">

**Please complete the following information:**
- Crater version: 6.0.6
- PHP version: 7.4
- Database type and version: MySql 8.0

**Optional info**
- OS:  Mac
- Browser: chrome

**Comment by mpember** [comment]
It is working for me.

What is the URL of the broken image in the last screenshot?

**Comment by gokultw** [comment]
<host>/storage/4/istockphoto-1151233834-612x612.jpeg

**Comment by mpember** [comment]
Is the file stored in the correct location? Correct name?

In my install, the URL is a complete URL, including the hostname.  Is your URL only partial? Or did you just leave that out when you posted you reply?

**Comment by mohitpanjwani** [comment]
Make sure that your APP_URL in the .env file is correct and also try running the the following command: `php artisan storage:link`

**Comment by vchrombie** [comment]
This issue is persisting in [demo.craterapp.com](https://demo.craterapp.com) as well. Is there any extra configuration that is needed?

**Comment by gokultw** [comment]
> 

this is the complete URL - https://payments-lite.mybahmni.in/storage/7/photo_2019-02-28_22-42-44.jpg

**Comment by gokultw** [comment]
> Is the file stored in the correct location? Correct name?
> 
> In my install, the URL is a complete URL, including the hostname. Is your URL only partial? Or did you just leave that out when you posted you reply?
> 

this is the complete URL - https://payments-lite.mybahmni.in/storage/7/photo_2019-02-28_22-42-44.jpg

**Comment by mpember** [comment]
> this is the complete URL

That is a different filename to the image you referenced in your earlier comment.  Did you upload a new image?

Are you able to access this URL in a browser?
Have you confirmed that the file is stored in the relevant path on the server?

**Comment by gokultw** [comment]
> That is a different filename to the image you referenced in your earlier comment. Did you upload a new image?

Yes the URL is different, I was not able to find the same customer so randomly opened a customer and posted the URL.

> Are you able to access this URL in a browser? 

404 NOT FOUND message displayed on accessing that URL

<img width="983" alt="image" src="https://user-images.githubusercontent.com/104197616/183822002-c37e762c-a231-4986-933c-4e6baa9be83e.png">

> Have you confirmed that the file is stored in the relevant path on the server?

@vchrombie - Could you please comment on this ?

**Comment by mpember** [comment]
> Could you please comment on this ?

You will need to look into the storage folder on the server hosting your instance of Crater.  If the file is not there, it may be that the folder permissions are incorrect and the file was unable to be saved.

**Comment by gokultw** [comment]
It seems like whenever a picture was uploaded, it was uploaded to crater-php. But when the image is shown on the crater, it's taken from crater-nginx. Official crater solves this by volume mounting the whole project folder in both of the docker containers.

As we don’t need the whole project volume mounted, the folder storing the images is volume mounted. In the case of crater-php, its /var/www/storage/app/public and for crater-nginx, its /var/www/public/storage. With these changes, issues with the company logo and profile picture were solved.
