### ISSUE TITLE
How can I remove crater logo from login page and on the header.. please help me with step by step, thankyou 

### ISSUE THREAD

**Issue by thahathafani** [crater-invoice/crater#999]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Comment by rihards-simanovics** [comment]
Please purchase a white label module for that: https://craterapp.com/modules/white-labe

**Comment by mohitpanjwani** [comment]
You can either purchase white label module or ask someone in the community for help regarding this (Maybe try our discord server)
